.gitmodules
Makefile
lib/net/Makefile
lib/net/nforceif/include/arch/cc.h
lib/net/nforceif/include/arch/sys_arch.h
lib/net/nforceif/include/lwipopts.h
lib/net/nforceif/src/driver.c
lib/net/nforceif/src/sys_arch.c
lib/net/pktdrv/license.txt
lib/net/pktdrv/pktdrv.c
lib/net/pktdrv/pktdrv.h
samples/httpd/Makefile
samples/httpd/httpserver.c
samples/httpd/httpserver.h
samples/httpd/main.c

This PR adds networking support to NXDK via [PktDrv](http://sourceforge.net/projects/openxdk/files/Patches%20and%20Drivers/AFL%20packet%20driver/) and the [LwIP](http://savannah.nongnu.org/projects/lwip/) networking libraries. A driver was created to interface LwIP and PktDrv. A simple HTTP server is included in the samples.

Networking

---

lib/hal/audio.c
lib/net/nforceif/src/sys_arch.c
lib/net/pktdrv/pktdrv.c
samples/0ldskoo1/flag.c
samples/0ldskoo1/main.c
samples/hello/main.c

I've fixed some warnings (or errors even) to make using NXDK easier.
Changes should be pretty self-explanatory
(There's a ton of warnings left - this was just the most annoying / important changes)

Fix warnings

---

Makefile

Fix invocation of CXBE in Makefile

Fix CXBE arguments

---

samples/sdl/main.c
tools/fp20compiler/ps1.0_grammar.y
tools/fp20compiler/rc1.0_grammar.y
tools/fp20compiler/ts1.0_grammar.y

Just a quick fix for a few warnings that annoyed me during my experiments. Changes are minimal and tested.

Warning fixes

---

lib/xboxrt/stdlib.c
lib/xboxrt/stdlib.h
lib/xboxrt/string.c
lib/xboxrt/string.h

Hello nxdk people!!
I'm currently writing a program to test xbox kernel apis (to test CxBx-R HLE kernel implementation), and while writing the configuration file parser, I realized that a couple of useful string functions were missing from nxdk.
So, this PR add these functions. Every of them are adapted from FOSS projects and contains a reference in comment.
I hope that everything is ok, I'm waiting for your verdict :P
Happy New Year,
Luca

Added a couple of useful string handling functions

---

samples/mesh/main.c
samples/triangle/main.c

Closes #45.
Small fix to make sure the samples doesn't automatically restart.

samples: Do not restart

---

tools/cxbe/Xbe.cpp

Copy-Paste of @JayFoxRox's upstream PR with very few 'cleanups'.
Closes #63 .

cxbe: Make cxbe compatible with default Xbox debug installations

---

lib/xlibc/include/_unimplemented.h

@thrimbor requested this commit to be cherry-picked into master. Here's the PR.
As described in his words:
> It's a small noninvasive (and working) addition that's required by #74 and #76 plus some stuff I work on locally.

xlibc: Add _unimplemented.h

---

lib/xboxrt/wchar.c
lib/xboxrt/wchar.h

Using the shepherd branch of pdclib, I ported over many of the wchar functions. This should replace my previous pull request which was looking to add a legacy wchar implementation in xboxrt.

xlibc: Add wchar.h

---

samples/hello++/Makefile
samples/hello++/main.cpp

A small sample showing off a working class structure with a custom constructor.

Add hello++ cpp sample

---

samples/0ldskoo1/Makefile
samples/hello/Makefile
samples/httpd/Makefile
samples/led/Makefile
samples/sdl/Makefile

Add GEN_XISO line to sample Makefiles

---

lib/sdl/Makefile

This updates our SDL submodule to the current HEAD (which merges upstream master). Makefile slightly adjusted to work with the newer version.

sdl: Update submodule

---

Makefile
lib/sdl/Makefile

As requested on Discord, this change was extracted from #106 as that one should focus on one thing instead of many.

Move SDL Makefile into submodule

---

lib/hal/led.c
lib/hal/led.h
samples/led/main.c

This was requested on Discord back in September of 2018.
I have no real hardware to test on ATM but it compiles without any warnings.

hal: Add LED API

---

samples/sdl/main.c

When #103 has been merged, a local `_exit()` declaration become extraneous.

sdlsample: Remove local _exit() declaration

---

tools/fp20compiler/main.cpp

Minor changes to fp20compiler output.

fp20compiler: Improve error output

---

lib/winapi/debug.c
lib/winapi/winbase.h
lib/winapi/windef.h
lib/winapi/winnt.h
lib/xboxkrnl/xboxdef.h
lib/xboxkrnl/xboxkrnl.h

Very useful function for getting data to a debugger.

Support OutputDebugString

---

lib/hal/fileio.c

Closes #146
Small change usable until the winapi stuff merges.

io: Allow opening the same file multiple times

---

lib/net/nforceif/src/driver.c
lib/net/pktdrv/pktdrv.c

Closes #128 
Untested code, although I have been running similar variations without problems.

net: Fix memory flags

---

lib/net/Makefile
lib/net/nforceif/include/lwipopts.h
lib/net/nforceif/src/driver.c
samples/httpd_bsd/Makefile
samples/httpd_bsd/httpserver.c
samples/httpd_bsd/httpserver.h
samples/httpd_bsd/main.c

The code in `httpserver.c` is inspired by [Beej's Guide to Network Programming](https://beej.us/guide/bgnet/).
Somewhat related to #15.

Samples: Add httpd bsd sample

---

samples/mesh/main.c

Closes #179 
Closes #182 
Closes #178 
I decided against also fixing #180 as it would need changes to the artwork or some new logic. We can fix this when we replace pbkit with a higher-level API or when fixing #181.
I've only tested this change in XQEMU. I did not do any tests on hardware.

Fix mesh sample bugs

---

Makefile
README.md

Updates extract-xiso from https://github.com/XboxDev/extract-xiso/commit/01fe0b682d0dc5ea0789ff7205c8ab977d67d91c to https://github.com/XboxDev/extract-xiso/commit/2da27caba8fda945a1c5013271c91f2f69da01f5 so we can profit from the fixes for warnings and errors that landed in the meantime.

extract-xiso: Update to latest master

---

lib/nxdk/mount.c
lib/nxdk/mount.h

Small but crucial fixes that became an issue when using the mounting functionality from C++ code.

Mounting fixes

---

lib/winapi/minwinbase.h
lib/winapi/sysinfo.c
lib/winapi/sysinfoapi.h

Implement GetSystemTime using KeQuerySystemTime.

winapi: Implement GetSystemTime()

---

lib/xboxrt/c_runtime/check_stack.c

- Make newlines more obvious
- Remove superfluous ')'

xboxrt: Improve stack-overflow message

---

README.md

Hi! 👋 
Just minor adjustments suggested by @JayFoxRox. 
- Referencing XboxDev in the readme, to point interested people towards the community
- ~~Stating the incompatibility with cxbx-r to prevent issues such as [Samples don't work in CXBX-Reloaded #352](https://github.com/XboxDev/nxdk/issues/352) in the future~~

docs: Update about XboxDev & cxbx-r in README.md

---

lib/nxdk/mount.c

nxdk: Fix nxUnmountDrive() returning true on error

---

lib/net/nforceif/include/lwipopts.h

I talked about this a bit in Discord already.
Before these changes, my router would treat the DHCP requests done by nxdk apps as coming from a different device, despite coming from the same MAC address as requests done by XDK apps. This lead to my router assigning a different IP address, which made it a bit annoying to connect.
These changes fix that by using a hook provided by lwIP to add two of the three DHCP option fields the XDK uses: The "Client identifier", which just contains an address type (0x01 for Ethernet) and the MAC address (this options seems to be the most important one to achieve this behavior), and the "Vendor class identifier", which just contains the non-terminated string "XBOX 1.0".
There is a third option that the XDK uses, "Requested IP Address", which contains the …

lwip: Add DHCP options to imitate XDK DHCP requests

---

README.md

Hi 👋 
This PR enhances the feature- and status-section in the `README.md` as proposed in #318

docs: Update README with new features list

---

lib/hal/video.c

This has been tested to cause no problems on xemu and a 1.1 Xbox. The project I used to test with is [https://github.com/Ryzee119/SDLPoPX](url).
Thanks to @kl0wn for looking into how this can be achieved!
Closes #357

video: Free framebufer of previous running app

---

lib/hal/video.c

The fixes of @GXTX as posted in #427 but with a better commit title.

hal: Code cleanup in video.c

---

lib/nxdk/Makefile
lib/nxdk/fatx.h
lib/nxdk/format.c
lib/nxdk/format.h
lib/xboxkrnl/xboxkrnl.h

This implements a FATX formatting function for volumes. I have formatted both FATX16 and FATX32 volumes with it and checked that the output matches the output of MS's code.

Implement volume formatting functions

---

lib/winapi/winnt.h

winapi: Fix XBE file header

---

lib/xboxrt/vcruntime/excpt.cpp

Small change silencing a few compilation warnings related to signed/unsigned comparisons.

vcrt: Fix sign related compilation warnings

---

lib/xboxrt/vcruntime/excpt.cpp

This fixes an error in our SEH implementation I noticed while working on C++ exceptions (it caused a crash there).
The error is that, instead of running the `__finally` funclet directly with the correct `ebp` value (funclets use `ebp`-relative addressing of local variables due to being called into from code that executes higher up on the stack), the code sets `ebp`and then calls `_local_unwind2`, which modifies `ebp` itself, leading to an incorrect value in the register when executing the funclet.
This causes all accesses to function-local variables by the funclet to read from or write to the stack frame of `_local_unwind2` instead of the function the funclet resides in.
To fix this, I introduced a wrapper function `call_ebp_func`, which handles calling a funclet with a specific …

vcruntime: Fix SEH _finally blocks running in wrong stack frame

---

lib/xboxkrnl/xboxkrnl.h

xboxkrnl: Fix type for MmGlobalData

---

lib/pkgconfig/zlib.pc

zlib: Fix pkgconfig

---

lib/hal/debug.c
lib/hal/debug.h

I got the original authors' permission to relicense this code under the MIT license. I can share proof of this on Discord on request, and have already shown it to @Ryzee119.

hal: Relicense debug code to MIT

---

lib/xboxkrnl/xboxdef.h

Fixes https://github.com/XboxDev/nxdk/issues/630

xboxkrnl: Implement NtCurrentThread()

---

lib/nxdk/automount_d.c

Fixes https://github.com/XboxDev/nxdk/issues/696.

nxdk: Prevent LTO stripping automount_d_drive

---

lib/pbkit/pbkit.c

I found this useful when debugging issues encountered in the nxdk_pgraph_tests project.

pbkit: Add detailed info to some limit exceptions
