- Makefile
With LLVM 4.x approaching most linux distros I figured we should use it as default on linux.
(I couldn't get mingw to work with NXDK anyway)
One major annoyance is that we don't have C++ support yet. So if it's easier to get that working with OpenXDK style mingw I'd be willing to switch this back.
[cgc has a binary available on Linux](https://developer.nvidia.com/cg-toolkit-download). So I decided to use that directly.
> Use native tools and LLVM on Linux

- lib/net/nforceif/src/sys_arch.c
#4 caused random crashes / hangs after about 10 minutes if the network code was active (See https://github.com/xqemu/nxdk/pull/4/files#r112821109 ).
This fixes it by implementing `sys_now` using `KeTickCount`.
---
Additionally this activates the `NtClose` to avoid leaking created semaphores.
The original commented out code had the `NT_SUCCESS` check negated (accidentally?) and always caused `abort`.
I'm assuming this negated condition was the original reason for the code being commented out.
---
(Only tested in xqemu yet, I'll test on hw later)
> Fix networking code bug / crash introduced by #4

- .gitignore
- Makefile
- README.md
- tools/vp20compiler/Makefile
This allows nxdk to be used on Windows using the MSYS2 shell.
Known Issues:
- Currently LLVM needs to be installed separately as the MSYS2 package is still on LLVM 3.9, as soon as LLVM 4.0 ships in MSYS2, this will no longer be required (this is why it is not mentioned in the readme)
- extract-xiso does not compile under MSYS2.
> Add Support for compiling on Windows (using MSYS2)

- Makefile
This patch adds the `/debug` flag to the linker when performing a debug build. This is necessary to instruct the linker to keep the debug symbol sections in the final binary.
> Add /debug linker flag for debug builds

- samples/led/Makefile
- samples/led/main.c
I've tried to construct the most basic example possible.
Having the LED code also helps for `printf`-style debugging.
However, this is primarily meant for those people who had crashes with other samples in nxdk.
Therefore, this sample does not require any video mode initialization and we can tell people to just remove 1 line from startup.c to test it without any AV code.
I'm aware that the code is somewhat cryptic and I hope we'll have a higher level API to control the LED in the future. For now, this will have to do.
> Provide a very basic LED sample

- .gitmodules
Closes #47.
nxdk-SDL has moved. Let the repository consider that.
> Move nxdk-sdl submodule

- lib/net/nforceif/include/lwipopts.h
- lib/xboxkrnl/xboxkrnl.h
- lib/xboxrt/stdbool.h
- lib/xboxrt/stdlib.c
- lib/xboxrt/stdlib.h
- lib/xboxrt/string.c
- lib/xboxrt/string.h
Changes necessary for xbe-loader, nxdk-rdt and other projects:
* This *should* fix our `free()` function which should make all nxdk programs more stable. Our existing `free` does not actually free memory. Could affect #35.
* It also fixes `strlen()` which broke many things for me. It used to return 1 for `strlen("")`. I've fixed and re-enabled `strdup` as a result.
* I also decided to enable LWIP DNS support, which required `atoi`.
* I also added a `bool` type to our stdbool.
* The mem* functions are now handled using the kernel Rtl functions. This should improve performance.
* I've addressed all sort of bugs in the xboxkrnl which prevented people from writing new drivers (this includes changing calling conventions and making `BOOL` a smaller type - most of our xboxkrnl structs were the …
> libc and xboxkrnl fixes

- Makefile
Closes #56.
As suggested by @thrimbor, changing `ld = lld-link` into `ld = lld -flavor link` makes the call work out of the box in Ubuntu.
> build: Change linux lld call name

- Makefile
- lib/Makefile
- lib/xlibc-rt/CREDITS.TXT
- lib/xlibc-rt/LICENSE.txt
- lib/xlibc-rt/_alldiv.s
- lib/xlibc-rt/_allmul.s
- lib/xlibc-rt/_allrem.s
- lib/xlibc-rt/_allshl.s
- lib/xlibc-rt/_allshr.s
- lib/xlibc-rt/_aulldiv.s
- lib/xlibc-rt/_aullrem.s
- lib/xlibc-rt/_aullshl.s
- lib/xlibc-rt/_aullshr.s
- lib/xlibc-rt/_fltused.c
- lib/xlibc-rt/check_stack.c
- lib/xlibc-rt/chkstk.s
This adds functions required at runtime by compiler generated function calls. Most of the 64-bit math code was taken from LLVM's compiler_rt library (required license files are included) and modified to fit the required calling convention.
I originally intended to use LLVM's __chkstk implementation too, but their implementation expects the OS to grow the stack when the guard page is hit during probing. However, on the Xbox, it seems that stacks are statically allocated, and while there is a guard page, it is only used to catch stack overflows - dynamic growth is not supported. So I wrote my own __chkstk implementation, which uses a C helper function to check whether the requested amount fits into the current thread's stack and prints an error if it doesn't.
I quickly tested it by running …
> Add libc runtime functions

- Makefile
- lib/Makefile
- lib/hal/fileio.c
- lib/xboxrt/stdbool.h
- lib/xlibc/include/_restrict.h
- lib/xlibc/include/assert.h
- lib/xlibc/include/setjmp.h
- lib/xlibc/include/stdarg.h
- lib/xlibc/include/stdbool.h
- lib/xlibc/include/stdnoreturn.h
- lib/xlibc/src/assert/_xlibc_assert.c
- lib/xlibc/src/setjmp/longjmp.s
- lib/xlibc/src/setjmp/setjmp.s
These are the first bits and pieces of my libc work. Additions mostly, without much replacing going on yet.
a6e0ec8cf355af94c8a1d6d9056dbca12a05ca26 adds the prerequisites for the later additions (include dir and source paths).
f3c9cbab073df536e18de2df525fd98db32524ca adds _restrict.h, which is meant as a libc-internal header to allow using the "restrict"-specifier while staying C++ compatible.
d89f109400cd4fe07d9290e8a6de6ac82d22b051 adds assert(). The standard actually says to call abort() (which would exit the program) which doesn't make much sense here, so the Xbox is halted instead. When compiled for a debug console (this isn't integrated with the makefile yet), RtlAssert is used instead of printing to the screen, and the Xbox is not halted in order to support tools like xbWatson, …
> libc additions

- lib/xlibc/src/setjmp/longjmp.s
This fixes a small oversight I noticed this morning: longjmp isn't allowed to make setjmp return zero, instead it should return one if the val-parameter was zero.
> Small fix for longjmp return value

- samples/sdl/main.c
The SDL sample contained stubs for _fltused, _aullrem and _aulldiv. While e30f9ffe9c6e3e9f4a8102f412dc9662cdcdb207 added a proper implementation, I forgot to remove the stubs, which broke linking for the SDL sample due to duplicated symbols. This PR fixes that by removing the stubs.
I also made sure the SDL sample really works by running it on my Xbox.
> Fix SDL sample building

- lib/xboxkrnl/xboxkrnl.h
BOOL should be a typedef of size int according to Microsoft Documentation: https://docs.microsoft.com/en-us/windows/desktop/winprog/windows-data-types#BOOL
> Update BOOL type to be correct size according to Microsoft Documentation

- .gitignore
This adds a few more patterns to .gitignore to reduce clutter when using `git status` or `git diff` (and to avoid adding them to the repository accidentally). .i, .bc and .pdb can be generated when instructing clang to save intermediate results, while .lib and .iso files in the samples-subdirectory are generated during a normal build but still shouldn't end up in the repository.
> git: Ignore more build artifacts

- .ci_build_samples.sh
- .travis.yml
Basically the same as #72, but with Travis instead of Appveyor and additional macOS support and without storing artifacts. macOS builds are rather slow compared to Linux builds (~8m vs ~1m) due to homebrew. It seems caching can be used to improve that, but messing with homebrew in that way is complicated and error-prone, so I didn't bother.
Travis doesn't seem to support msys ootb, therefore I didn't try adding Windows support.
Also addresses #36.
> CI: Add Travis CI support for Linux and macOS

- Makefile
- tools/cxbe/Xbe.cpp
Currently, cxbe always sets dwPeStackCommit to 64KiB (which is the default value of Microsoft's XDK), while our intermediate PE files have m_sizeof_stack_commit set to 4KiB and m_sizeof_stack_reserve to 1MiB. This didn't cause us any problems yet afaik, but this commit fixes it anyway.
I already briefly talked about this on Discord last October:
> I think I figured it out
> PE has SizeOfStackCommit and SizeOfStackReserve. SizeOfStackReserve is the maximum stack size, while SizeOfStackCommit is the initial stack size, meaning only SizeOfStackCommit bytes get reserved in the beginning, and the rest is only mapped when required, at least on Windows.
> But the Xbox doesn't allow growing the stack dynamically, so it only has SizeOfStackCommit. So for the Xbox, it's XBE.SizeOfStackCommit = …
> Properly set XBE stack size

- Makefile
- lib/hal/audio.h
- lib/hal/fileio.h
- lib/hal/input.h
- lib/hal/io.h
- lib/hal/mouse.h
- lib/hal/pad.h
- lib/hal/video.h
- lib/hal/xbox.h
- lib/pbkit/pbkit.h
- lib/xboxkrnl/xboxkrnl.h
- lib/xboxrt/debug.h
- lib/xboxrt/stat.h
- lib/xboxrt/strings.h
This adds basic C++ support by adding rules to the Makefile, adding `extern "C"` where necessary to get the name mangling right and renaming struct fields in the xboxkrnl-header.
Global constructors are already handled by my PDCLib-additions, so when this PR is combined with https://github.com/XboxDev/nxdk-pdclib/pull/2, simple code like [this](https://gist.github.com/thrimbor/62a550b36cb5ab65a7b6ceacc4fbd084) already works.
Note that CI on macOS currently fails due to the problem described in https://github.com/XboxDev/nxdk-pdclib/pull/1, this affects Arch Linux now, too. It works on the Ubuntu CI, though.
> Add (rudimentary!) C++ support

- README.md
Unfortunately OpenXDKs sourceforge page has been hacked (for some time), this will instead provide a link to a archive.org snapshot.
This has already been updated on https://xboxdevwiki.net/.
> docs: Update OpenXDK link on readme.md

- Makefile
- tools/fp20compiler/Makefile
- tools/fp20compiler/ps1.0_tokens.l
- tools/fp20compiler/rc1.0_tokens.l
- tools/fp20compiler/ts1.0_tokens.l
This fixes #96 (although removing the `.iso` should work already) as well as some other issues such as broken parallel make. It also combines the rules for dependency file generation and compilation to avoid running the compiler twice - this also resolves the issue of `make distclean` generating dependency files only to immediately remove them again.
> Make improvements

- samples/sdl_ttf/main.c
Updated the SDL2 submodule.
The sdl_ttf sample received an update too in order to reflect these changes.
The main SDL sample did not change however as its `_exit` differs in functionality from the PDClib one.
> Sdl: update submodule

- Makefile
- lib/Makefile
- lib/winapi/error.c
- lib/winapi/memory.c
- lib/winapi/memoryapi.h
- lib/winapi/winbase.h
- lib/winapi/windef.h
- lib/xboxkrnl/xboxdef.h
- lib/xboxkrnl/xboxkrnl.h
This adds some simple parts of the WinAPI, namely error handling and virtual memory handling.
This originally was part of my work on the file finding API (mentioned in Discord), but I decided to split it out as I required it for my current work on integrating dlmalloc (which recently got added to PDCLib to replace the old primitive malloc) - since dlmalloc already supports Win32, this makes it much easier to build for nxdk.
The code has received testing as part of my work on my other branches.
> WinAPI error and memory functions

- tools/fp20compiler/main.cpp
Fix for corruption at the end of fp20compiler's output when running under Windows (as ranted about on Discord). The changes are:
1. Open input stream as binary to avoid line ending conversion issues.
2. Reserve an additional byte to make space for a null-terminator.
3. Add a null-terminator after reading the input.
Tested and working on msys2 on Windows 10.
> fp20compiler: Fix corrupted output on Windows

- lib/hal/fileio.c
This helper function is useful but when not needed it gets in the way.
By checking if the input filename already is in Xbox format, we might return early with a STATUS_SUCCESS.
This code was originally written by @JayFoxRox for JayFoxRox/nxdk#7
> hal: Allow xbox paths in XConvertDOSFilenameToXBOX

- lib/net/pktdrv/pktdrv.c
- lib/net/pktdrv/pktdrv.h
Get rid of a magic number and give these values proper types instead of just defining them in macros.
Code originally written by @JayFoxRox for JayFoxRox/nxdk#7.
> pktdrv: PktdrvInterrupt and MmioBase as extern instead of macros

- Makefile
This simply changes the debug parameter from `/debug` to `-debug` which makes it work on Windows.
Tested and working on msys2 on Windows 10.
> build: Fix debug option on Windows

- lib/xboxkrnl/xboxkrnl.h
Cleans up all the remaining tab-characters. This is a formatting change only.
> xboxkrnl: Whitespace cleanup

- Makefile
LLVM's default behavior seems to have changed, making it necessary to explicitly request DWARF debug info for source level debugging as described in the wiki.
Tested with clang 8.0.
/edit:
This specifies DWARF 4, which is the most recent working version - attempting to use DWARF 5 crashes clang 8.0.
> build: Explicitly request embedded DWARF debug info

- lib/pbkit/pbkit.c
For some odd reason the existing pbkit code allocates one zeta buffer per framebuffer.
This is stupid because there's rarely any situation where you need to use the z-buffer of a framebuffer that isn't currently being drawn.
Using one shared buffer reduces memory usage.
Additionally the existing code used the color-buffer size instead of the z-buffer size.
> pbkit: Only allocate a single depth buffer

- tools/vp20compiler/main.c
The final vs.inl currently doesn't contain the VS variable / constant locations that the Cg vertex program uses. That's an issue as it's necessary to set up a working program.
This adds a small loop, which collects all comments, and forwards them from input to output.
Unfortunately, this is not position aware, so it won't interleave encoded instructions and comments. But it's still good enough to read back the `#var` and `#const` lines.
It isn't really secure, and it's probably easy to write malicious code which outputs garbage C code (like introducing `/*` as part of the comment).
Ideally we'd parse only those important lines and generate a `float c[][4];` and code which uploads it; however, this will have to do for now.
This was barely tested, but should work fine.
---
As an alternative …
> vp20compiler: Forward comments from input to output

- lib/usb/sys/xpad.c
As kindly explained by JFR, this change ought to enable most (if not all) Xbox compatible controllers instead of just the few identified earlier.
> xpad: Match interface instead of VID/PID

- samples/hello++/main.cpp
- samples/hello/main.c
- samples/httpd/main.c
- samples/mesh/main.c
- samples/sdl/main.c
- samples/sdl_ttf/main.c
- samples/triangle/main.c
- samples/winapi_filefind/main.c
This will be required when XboxDev/nxdk-pdclib#3 is merged and
`XVideoSetMode()` in `crt0.c` has been removed.
Not suitable for merge before then, do want to update the submodule in this same PR.
> samples: Add XVideoSetMode()

- lib/xboxkrnl/xboxdef.h
- lib/xboxkrnl/xboxkrnl.h
Small number of fixes for `xboxkrnl.h` and `xboxdef.h`.
* Small cleanup of redundant typedefs
* DWORD typedef fix by @mborgerson, cherry-picked from https://github.com/mborgerson/dc27-dooom-nxdk/commit/ac22514420cf9b2f610566d615f570b502d71558
* `MAXDWORD` macro added (needed by libc++)
> xboxkrnl fixes

- lib/xboxkrnl/xboxkrnl.h
Title pretty much says it all. Fixes a warning when passing a string literal to the function.
> xboxkrnl: DbgPrint() takes a constant string parameter

- Makefile
- samples/httpd/Makefile
- samples/sdl/Makefile
- samples/sdl_ttf/Makefile
The update to LLVM 9 on macOS broke CI. Problem described [here](https://github.com/XboxDev/nxdk/pull/154#issuecomment-535107218).
There are two underlying issues here:
1. LLVM 9 seems to default to enforcing [Safe SEH](https://docs.microsoft.com/de-de/cpp/build/reference/safeseh-image-has-safe-exception-handlers?view=vs-2019). It's meant to prevent hijacking of the control flow by overwriting the exception handling record (which resides on the stack) and then triggering an exception. Safe SEH protects against that by checking the handler address in the exception handling record against a list containing all the handlers. nxdk doesn't support Safe SEH (we don't even have normal SEH yet), so my solution is to disable Safe SEH in the linker (which doesn't prevent using or implementing Safe …
> Fix macOS CI

- lib/hal/debug.c
- lib/hal/debug.h
- lib/hal/video.c
- lib/pbkit/pbkit.c
- lib/pbkit/pbkit.h
This allows users to control the pbkit framebuffer color format (prior to `pb_init`). To make this more useful, R5G5B5 output is added to our video code.
The `debugPrint` code also wasn't aware of this mode, so I added some code to handle it.
This is a temporary API, as we'll have to make many more changes to the pbkit surface API in the future (as it doesn't really allow non-framebuffer rendertargets except the flawed `extra_buffer` code). However, such refactors will be in future PRs.
A similar PR for the zeta buffer will follow in the near future.
> pbkit: Allow setting color surface format

- .gitignore
- Makefile
- lib/Makefile
- lib/Makefile-pdclib
- lib/hal/Makefile
- lib/sdl/Makefile
- lib/usb/Makefile
This splits out `PDCLib`, `hal`, `Freetype` and `SDL_ttf` to be built as libraries (others are untouched to avoid getting too many merge conflicts).
I am well aware that this is still far from being a complete solution (everything is built with the same compiler flags, libs are automatically added by makefiles instead of the samples specifying their requirements, still the one large main Makefile, sub-Makefiles adding cleaning rules to the main Makefile via a variable etc.) - I consider this only a first step and, most importantly, a fix to get nxdk to build on msys2 again.
> Libraryization

- samples/mesh/main.c
- samples/triangle/main.c
Closes #184 
Fixes VP upload errors in the samples:
**Uploads the correct number of instructions now.**
This used to be miscalculated which caused overflows.
**Uploads each instruction in its own `pb_begin` / `pb_end` block.**
This avoids long pbkit blocks; pbkit warnings suggest that 128 DWORDs is the maximum number of DWORD per block. I believe this is the GPU cache size, although I don't think the hardware would struggle when submitting more. For now, we'll just respect this pbkit limit (it will be enforced using `assert` by #158), but we should eventually review why it exists.
---
I've only tested this in XQEMU
> samples: Fix VP upload

- Makefile
The idea is so that if someone includes our makefile, they can use `NXDK_*FLAGS` if they want to call the tools themselves.
Additionally, the nxdk makefile can then be interacted with using standard `*FLAGS` variables, without them being modified by nxdk (in case the makefile that included nxdk makefile wants to use them again).
This is still very dirty, but a bit more consistent and predictable.
I've also added the `-MP` flag to avoid errors which would appear after building with a feature-branch (which had headers which are missing when switching back to master): 
```
$ make
make: *** No rule to make target 'nxdk/samples/triangle/../../lib/xgu/xgu.h', needed by 'nxdk/samples/triangle/main.obj'.  Stop.
$
```
> makefile: Cleanup

- tools/fp20compiler/rc1.0_final.cpp
- tools/fp20compiler/rc1.0_general.cpp
This was already a PR #138 but I got suspicious about my fix and closed it. I have now tested this on hardware and cleaned up my fix. I've [documented my findings in XboxDevWiki](https://xboxdevwiki.net/NV2A/Pixel_Combiner#Encoding_of_input_swizzle) and implemented the described behaviour.
The correct condition for the ALPHA flag should be `reg.reg.bits.channel == RCP_ALPHA`.
This condition is already being used for final-combiner inputs:
https://github.com/XboxDev/nxdk/blob/80315410cfbbee778560f4bb92821970ffe99e4b/tools/fp20compiler/rc1.0_final.cpp#L117-L118
However, the `//TODO: Blue` is misleading as it already handles `RCP_BLUE` correctly (only allowed for scalar input `G`; vector inputs `A`-`E` allow `RCP_RGB` instead); the ALPHA flag would be 0 as expected.
This PR copies the …
> fp20compiler: Fix input component selection

- tools/fp20compiler/ts1.0_inst_list.cpp
**Fix bug in texture-dependency code emitter**
This was noticed in https://github.com/XboxDev/nxdk/pull/187#issuecomment-538559944 and needs to be fixed for #158.
The command to set the texture stage inputs (if a texture stage depends on results of an earlier stage) was previously overwritten by the next command, as `p` was not advanced.
The de-synchronization of `p` and the internal pbkit state will cause `assert(false)` to be hit in `DBG` mode after #158.
**Support texture-dependencies**
After the fix above, it was noticed that texture-dependencies definitely wouldn't work correctly.
The old code ignored information from the shader and hardcoded mappings.
The new code does what the shader requests.
See https://www.nvidia.in/attach/6371 or …
> fp20compiler: Support texture-dependencies

- lib/sdl/Makefile
Closes #201 
This fixes building C++ apps with SDL_ttf and freetype.
We'd need an update to the nxdk-sdl repo too for it to work all out though.
XboxDev/nxdk-sdl#12 could be that fix.
> Cpp build fix for SDL_TTF and friends

- lib/hal/video.c
- lib/hal/video.h
When a video setting has been selected and stored to EEPROM it should be respected.
> video: Respect EEPROM video settings

- .travis.yml
- .travis_win_build.bat
- .travis_win_deps.bat
Based on #156.
The only change compared to #156 is b9f3204d6eac7c762cf4c4e2cf7ce03005be8505, which adds support for building with msys2 on Windows with Travis CI. It uses the Chocolatey package manager for msys2 installation (also includes a hang workaround, see https://travis-ci.community/t/build-times-out-when-msys-was-installed/3498), the additional batch files were required because of whitespace issues when calling bash directly from `.travis.yml`.
Due to slower building and the time required to install msys2, this runs quite a bit slower than the Linux build and is even about a minute slower than the macOS build, but it works.
> Travis CI for Windows/msys2

- samples/hello++/main.cpp
- samples/hello/main.c
- samples/httpd/main.c
- samples/httpd_bsd/main.c
- samples/led/main.c
- samples/mesh/main.c
- samples/sdl/main.c
- samples/sdl_ttf/main.c
- samples/triangle/main.c
- samples/winapi_filefind/main.c
This PR
1. changes samples to int main() from void
2. removes XReboot() from main as pdclib handles this after returning form main
Fixes #91 
Some of the samples were returning -1 on pb_init() failure, @JayFoxRox suggested returning 1 for failure so I've made that change, but that can be up for discussion if others disagree
> Remove XReboot and return value from main

- tools/fp20compiler/rc1.0_combiners.cpp
- tools/fp20compiler/rc1.0_general.cpp
- tools/fp20compiler/rc1.0_general.h
Closes #132.
For background infomation, see [this XboxDevWiki article for a description of register-combiners](http://xboxdevwiki.net/NV2A/Pixel_Combiner#Register_combiners).
The old emitter code..
- ..erroneously chose per-stage constant-colors (`FACTOR#_EACH_STAGE` instead of `FACTOR#_SAME_FACTOR_ALL`), depending on number of constant-colors defined in global scope. Instead, this selection should depend on the number of local-colors (per-stage) instead. This needed a larger refactor, see below.
- ..emitted code had a typo for final combiner `const1` which lead to compilation errors if it was used.
- ..pushed colors in 4 floats. This is wrong and caused GPU command overflows / garbage colors.
- ..updated wrong constant in almost any case (used wrong variable in emitter-`printf`).
This PR …
> fp20compiler: Fix constant-color emitter

- lib/xboxrt/Makefile
- lib/xboxrt/libc_extensions/string_ext_.c
- lib/xboxrt/libc_extensions/string_ext_.h
Like #185, this is supposed to use the new PDCLib extension hooks once they're merged, see that PR for details.
This adds `strdup` and the MS-specific alias `_strdup`. While not part of the C standard (yet, C2x will probably add it), it's required by libc++.
/edit:
Using the extension hooks for this can be tested by adding `#define _PDCLIB_EXTEND_STRING_H <string_ext_.h>` to `platform/xbox/include/pdclib/_PDCLIB_config.h` in the PDCLib directory after checking out my branch from https://github.com/XboxDev/nxdk-pdclib/pull/12.
> libc: Add strdup / _strdup as extensions

- lib/xboxrt/libc_extensions/errno_ext_.h
This adds `errno_ext_.h`, which, with the help of the extension hook system, ensures that `errno_t` always defined when including `errno.h` (as expected by libc++).
> libc: Add extension to always define errno_t in errno.h

- lib/xboxrt/libc_extensions/stdio_ext_.h
This adds `stdio_ext_.h`, which, with the help of the extension hook system, defines `_vsnprintf`, which is a Microsoft-specific alias for `vsnprintf`, and is required by libc++.
> libc: Add extension to provide _vsnprintf alias

- .travis.yml
Apparently something changed in Travis CI, chocolatey or msys2, which results in `gpg-agent.exe` no longer being around. This makes `taskkill` fail, which fails our builds currently.
Since I'm not sure why this is the case and whether it's going to stay that way, I added `|| true` to make it no longer fail the build instead of removing it completely.
I expect this to get replaced by #168 anyway.
> ci: Fix Travis on Windows by ignoring whether taskkill failed

- lib/pbkit/pbkit.c
- lib/pbkit/pbkit.h
- samples/mesh/main.c
- samples/triangle/main.c
- Remove the old `pb_push` macro
- Remove some of the repeated code
- ~~Define functions as `inline`~~
- Return a new pointer, remove the need for manual pointer incrementation
- Update the `mesh` sample to use these new capabilities
- Update the `triangle` sample to use these new capabilities
> pbkit: pb_push refactor

- samples/hello++/main.cpp
- samples/hello/main.c
- samples/httpd/main.c
- samples/httpd_bsd/main.c
- samples/sdl/main.c
- samples/sdl_ttf/main.c
- samples/winapi_filefind/main.c
Closes #212
Edit: Closes #90
Edit2: Copied from 212:
**H**owever, there's one exception why we might still need pbkit (or a minimal GPU driver):
I'm not sure if it can happen, but maybe the GPU can be left in a bad state when switching applications. That could have side-effects in RAM. To avoid that, we'd have to stop the GPU at startup. Currently, pb_init takes care of such things.
Someone should construct a test to see if this is an issue.
> samples: Remove pb_* from samples not using pbkit

- Makefile
This upstreams these two necessary changes from my libc++ branch:
* Thread-safe initialization of static variables gets disabled. C++11 by default guarantees that static variables will get initialized in a thread-safe way the first time they're encountered, but this relies on functions we do not provide yet. This should be easy to tackle properly after adding C++11 thread support.
* RTTI generation gets disabled. Generating RTTI causes references to internal data structures that aren't in place yet. This can get re-enabled once we implement these (which will happen together with exception support).
Both changes are necessary to avoid linker errors when using libc++.
> C++ Makefile changes

- lib/xboxkrnl/xboxkrnl.h
- lib/xboxrt/Makefile
- lib/xboxrt/libc_extensions/stdlib_ext_.c
- lib/xboxrt/libc_extensions/stdlib_ext_.h
This implements the rand_s function, which is a MS-specific function required by libc++. To keep the executable size small and the code simple, it uses the kernel's SHA-1functions which are fed with the EEPROM contents, the TSC and the tick counter (the latter two are also used each time a new random number is requested).
The global state is initialized once by using `call_once` and protected by a mutex. Each time a random number is requested the hash is updated by feeding in the TSC and the tick counter, then the first four bytes of the output hash are extracted and returned as the random number, while also being fed back into the hash.
Security could of course be improved by adding additional entropy sources.
This PR conflicts with #185 as they touch the same file.
The CI failure is …
> Implement rand_s

- lib/pbkit/pbkit.c
- lib/pbkit/pbkit.h
- samples/mesh/main.c
Fixes #175.
This doesn't replace all occurrences of `DWORD`, only those that currently produce warnings. Tested samples continued to work as they did before.
> pbkit: Fix type warnings by replacing DWORD with uint32_t

- lib/xboxrt/libc_extensions/stdio_ext_.h
Tiny change to add the MS-specific `_snprintf` alias. This requirement came up when I experimented with TinyXML2.
> libc: Add _snprintf alias

- tools/fp20compiler/main.cpp
Refactor of #115 
Closes #113 
**Motivation:**
- Makes it easier to write shader assembly from scratch, without cgc (old code used cryptic end-of-shader markers).
- Allows us to more easily add more shaders (like adding further pipeline state shaders).
- Output is annotated, which will help when supporting more shaders per file.
- Allow us to more easily add per-shader things in the future (like error reporting, see #189).
- Line counting allows us to offset the existing line-in-shader `line_number` with the line-in-input `shader_line_number` (also good for error reporting).
**Changes from #115:**
- Correctly escapes comments and `\r` in shader magic line now (See https://github.com/XboxDev/nxdk/pull/115#issuecomment-543362108).
- Copies strings instead of temporarily modifying a global …
> fp20compiler: Refactor translation function

- Makefile
- lib/xboxrt/Makefile
- lib/xboxrt/vcruntime/vcruntime_exception.cpp
- lib/xboxrt/vcruntime/vcruntime_exception.h
- lib/xboxrt/vcruntime/vcruntime_typeinfo.cpp
- lib/xboxrt/vcruntime/vcruntime_typeinfo.h
Another PR with changes from my libc++ branch.
On Win32, `std::exception` (and a few classes inheriting from that) and `std::type_info` are actually implement as part of vcruntime, and not the C++ standard library. libc++ also relies on these vcruntime implementations, so this implements the required classes and functions.
I copied the behavior of MS's functions as good as I could and copied their naming of private member variables and functions. I also added one MS-specific extension, the `(const char *const, int)` constructor for `std::exception` - this constructor gets a second parameter, which is actually ignored, and only used to overload the constructor in order to be able to avoid string buffer allocations when creating an exception object, which saves memory and allows exceptions …
> vcruntime exception and type_info classes

- lib/xboxrt/Makefile
- lib/xboxrt/libc_extensions/stdlib_ext_.h
- lib/xboxrt/vcruntime/purecall.c
This is a very MS and C++ specific piece of code - unfortunately, it's impossible to test this meaningfully without some large parts of my libc++ work (we would need to try and call a pure virtual function, but such code will emit RTTI references we don't provide yet).
As the name suggests, clang will emit code calling `_purecall` whenever the program tries to call a pure virtual function. The program is able to set it's own handler (which should never return), but there also has to be default handling (we're just printing info here and enter an endless loop).
As for the new header: While being considered part of vcruntime, `_get_purecall_handler` and `_set_purecall_handler` are supposed to be provided by `stdlib.h`. To not clutter PDCLib with non-standard stuff, I have spoken with …
> vcruntime: Add pure virtual function call handling

- lib/pbkit/pbkit.c
The functions  `pb_target_back_buffer` and `pb_target_extra_buffer` do exactly the same thing, just for different buffers. GL would call these `DrawBuffer`, so I've factored out this code under that name.
The diff between the original functions was this:
```diff
@@ -1,4 +1,4 @@
-void pb_target_back_buffer(void)
+void pb_target_extra_buffer(int index_buffer)
{
DWORD           *p;
@@ -13,6 +13,12 @@ void pb_target_back_buffer(void)
int         flag;
int         depth_stencil;
+
+    if (index_buffer>=pb_ExtraBuffersCount)
+    {
+        debugPrint("pb_target_extra_buffer: buffer index out of range\n");
+        return;
+    }
width=pb_FrameBuffersWidth;
height=pb_FrameBuffersHeight;
@@ -20,7 +26,7 @@ void pb_target_back_buffer(void)
pitch_depth_stencil=pb_DepthStencilPitch;
//DMA channel 9 …
```
> pbkit: Avoid redundant code for targeting draw-buffers

- .gitignore
fp20compiler compilation creates all these additional files:
```
_ps1.0_lexer.cpp _ps1.0_lexer.o
_ps1.0_parser.cpp _ps1.0_parser.h _ps1.0_parser.hpp _ps1.0_parser.o
_rc1.0_lexer.cpp _rc1.0_lexer.o
_rc1.0_parser.cpp _rc1.0_parser.h _rc1.0_parser.hpp _rc1.0_parser.o
_ts1.0_lexer.cpp _ts1.0_lexer.o
_ts1.0_parser.cpp _ts1.0_parser.h _ts1.0_parser.hpp _ts1.0_parser.o
```
We caught most files in our existing top-level .gitignore.
However, the .hpp files were not caught by our .gitignore; this PR fixes that.
> git: Ignore generated C++ headers

- .gitignore
I've noticed that the SDL_ttf samples "bin" directory is found dirty after compilation.
That is because it contains a ".ttf" file.
Other samples aren't considered dirty, because we ignore ".xbe" files, so git considers those other "bin" folders empty.
This adds the "bin" directories to .gitignore to avoid this (and similar issues).
> git: Ignore "bin" directories

- tools/fp20compiler/main.cpp
- tools/fp20compiler/nvparse_errors.cpp
- tools/fp20compiler/nvparse_errors.h
- tools/fp20compiler/rc1.0_final.cpp
- tools/fp20compiler/rc1.0_general.cpp
- tools/fp20compiler/rc1.0_register.h
**Avoid sharing of token for ZERO and DISCARD register**
We currently don't report fp20compiler (nvparse) errors.
However, if we enable error reporting, we'd always get `error: reading from discard` and `error: invalid input register for final rgb`. These errors result from modifcations for Xbox.
nvparse uses `RCP_*` structs to describe details of a hardware register (register-number, read-only, ...). The original GL code in nvparse used different register numbers (`GL_ZERO=0` and `GL_DISCARD=0x8530`) for `REG_ZERO` and `REG_DISCARD` (used in the respective `RCP_*` struct).
In fp20compiler, the `GL_` constants have been replaced by `REG_ZERO=0` and `REG_DISCARD=0` (so `RCP_ZERO` and `RCP_DISCARD` share the same `REG_*` register-number).
This was done because Xbox hardware register 0 …
> fp20compiler: Report nvparse errors

- lib/xboxrt/libc_extensions/ctype_ext_.h
This adds the (obsolete but required by libc++) function `isascii()`, as well as some macros libc++ expects `ctype.h` to provide. The actual values of these defines were retrieved by running tests in VS 2019.
> libc: Provide isascii() and required macros via ctype.h

- samples/sdl/main.c
- samples/sdl_ttf/main.c
The SDL samples weren't including `hal/debug.h` so the compiler warned about implicitly declaring `debugPrint`, this adds the include statement to fix that.
> samples: Fix warnings about implicitly declaring debugPrint()

- lib/xboxrt/libc_extensions/stdlib_ext_.h
Win32 provides a macro called `_sys_nerr` to get the highest valid errno value. libc++ requires this, so this commit provides it.
> libc: Provide _sys_nerr macro via stdlib.h

- lib/xboxrt/libc_extensions/stdlib_ext_.c
libc++ depends on the presence of these three functions. PDCLib doesn't provide them yet, so this provides stubs until the functionality is in place. I added asserts to catch calls to these functions instead of silently returning invalid results, but these functions were never called by libc++ itself during my tests.
> libc: Add stubs for strtod(), strtof(), strtold()

- lib/xboxrt/libc_extensions/locale_ext_.h
This adds the necessary stubs for functionality libc++ expects from `locale.h`. `_create_locale` is actually ran by libc++ when using it, so this code is somewhat tested.
> libc: Add locale.h extensions required by libc++

- lib/xboxrt/Makefile
- lib/xboxrt/libc_extensions/wchar.c
- lib/xboxrt/libc_extensions/wchar.h
- lib/xboxrt/libc_extensions/wchar_ext_.c
- lib/xboxrt/libc_extensions/wchar_ext_.h
This adds all the stubs in `wchar.h` required by libc++. The PDCLib update is included, because it's required for this to work (the PDCLib update includes the typedefs in `wctype.h`).
This probably is the last preparation PR for libc++.
> wchar stubs & PDCLib update

- lib/hal/fileio.c
This fixes a bug that was [reported by KingLuxor on Discord](https://discordapp.com/channels/428359196719972353/428360618102226946/652594555832631308).
> Seeing an issue with fopen() when using Evox M8/IND-Bios, say the filename is flash.bin the file that gets created is xenium-tools.xbesk[flash.bin
> it works just fine using X2 BIOS, just wanted to pass the info along
This affects https://github.com/Ryzee119/OpenXenium/tree/master/Xenium-Tools; a code review revealed no issues in Xenium-Tools. However, I did spot a bug in nxdk where we don't zero-terminate the `XeImageFileName` using it's length (instead, we treat it as zero-terminated string - which it isn't).
This leads to garbage being added to the string (might overflow `currentDirString`), and `\` might be found outside the string, …
> hal: Respect XeImageFileName->Length in getCurrentDirString()

- tools/cxbe/Main.cpp
- tools/cxbe/Xbe.cpp
- tools/cxbe/Xbe.h
This fixes some of the worst bugs in cxbe:
* Fixes dates, as cxbe uses `time_t` pointers to read from the XBE. `time_t` is larger than 4 bytes value on my platform, but the XBE only stored 4 byte timestamps. This meant we also read neighboring fields (and got bad timestamps).
* Fixes bug where our stubbed conversion from UCS-2 to ASCII left the string without zero-termination (causing buggy output on terminal). This is just a hotfix - we'll eventually have to fix the conversion routines and factor out common code (the code exists 2 times).
* Fixes bug where UCS-2 name was only zero-terminated in the first 20 symbols, after that, garbage could have followed, so any name above 20 symbols might have expanded to up to 40 symbols.
* Fixes bug where 256 symbols could be entered for XBE name, …
> Fix some cxbe bugs

- tools/fp20compiler/rc1.0_combiners.cpp
- tools/fp20compiler/ts1.0_inst_list.cpp
Generated output from fp20compiler always depended on a user defined `MASK` macro.
This PR adds the macro to the shader.
The macro uses `__builtin_ffs` so that the user doesn't need to include `strings.h`, however, the user still has to include `pbkit.h`.
*(Another implementation would be to add a new function: `pb_mask` for example. However, I wanted a lightweight solution for now - we can improve it later)*
> fp20compiler: Add `MASK` macro to output

- tools/fp20compiler/rc1.0_combiners.cpp
- tools/fp20compiler/rc1.0_general.cpp
Closes #216 
I was originally going to send another PR right now, but then I noticed that the planned PR hides the bug explained in #216 (but does not fix it).
This PR aims to fix #216 and adds more asserts to catch such errors in the future.
If a constant-color is set twice, the later one is used; the first color value is discarded.
*(Although the error message should discourage the user from setting colors twice anyway)*
> fp20compiler: Avoid overflow bug with duplicated constant-colors

- lib/nxdk/Makefile
During the refactoring of #230 I accidentally introduced a typo in one of the cleaning rules, which broke `make clean`. This fixes the typo in the rule name.
> build: Fix typo breaking make clean

- tools/fp20compiler/ps1.0_grammar.y
- tools/fp20compiler/rc1.0_combiners.cpp
- tools/fp20compiler/rc1.0_final.cpp
- tools/fp20compiler/rc1.0_general.cpp
- tools/fp20compiler/rc1.0_general.h
- tools/fp20compiler/rc1.0_grammar.y
- tools/fp20compiler/rc1.0_register.h
- tools/fp20compiler/rc1.0_tokens.l
- tools/fp20compiler/ts1.0_grammar.y
There should be no changes in behaviour, but:
- Adds line numbers to error messages.
- Provides more explicit error messages.
- Refactors code so code duplication is minimized.
All of the refactoring is contained in the final-combiner commit. I hope I didn't break anything. The code should be reviewed to make sure.
*This is the PR that has been mentioned in #240:
If this PR would have come first, it somehow would have prevented the issue explained in #216 (no more assert or crash).
I'm not sure why that happened, but I assume the structs get packed differently, so that the colors actually overwrite the color count.*
---
You can find shaders for testing (and a tool to run them) in this branch: https://github.com/JayFoxRox/nxdk/pull/56
Some of those tests annotations might not mention some …
> fp20compiler: Improve error messages for register-combiners

- lib/net/Makefile
- lib/net/nforceif/include/arch/sys_arch.h
- lib/net/nforceif/include/lwipopts.h
- lib/net/nforceif/src/driver.c
- lib/net/nforceif/src/sys_arch.c
- samples/httpd/main.c
- samples/httpd_bsd/main.c
This pretty much does what the title says - instead of using some random commit before the 2.0.0 release, this updates our lwip submodule to the latest stable release. Some changes were necessary for this, and I'll leave review comments with the details.
This PR intentionally doesn't touch any areas where we could optimize or clean up things or utilize features of newer releases - I focused only on updating the submodule without introducing regressions.
I tested this with our two http server samples on my 1.0 Xbox.
> lwip: Update submodule to STABLE-2_1_2_RELEASE

- .ci_build_samples.sh
Simple addition to our CI build script to let `make` use parallel jobs (where the number of jobs equals the number of cores). Roughly halves the build time (not the total job time, though).
> ci: Utilize all cores for building

- .github/workflows/build_samples.yml
Pretty much the same thing @mborgerson set up for xqemu, I copied the config changes from him. The msys2 environment was adjusted to contain the packages nxdk needs, and while it's much larger than the xqemu version, it still reduces the time required a lot while also working around chocolatey reliability issues.
> ci: Use cached msys2 environment

- lib/hal/video.c
- lib/hal/video.h
- samples/gamma/Makefile
- samples/gamma/README.md
- samples/gamma/main.c
This is something I've played around with recently; as also described in the README, this isn't exactly useful on Xbox, but might still be useful in niche situations or for "free" effects (fades, color filters, flashes, ..).
As this is adding to the hal/video API I wasn't too focused on making this clean.
I chose a `memcpy` style API for now.
The sample has some ugly bits which will need to be improved in the future (the sample image is poorly chosen for a gamma test *and* tone-mapping). Ideally we'll be loading a couple of different images from memory.
In the XDK, this is exposed by D3D (presumably). However, it makes sense to expose this together with video-encoder features as it's not part of the rendering, but display routines.
---
I have not tested this with 16bpp modes yet. I'm not …
> Gamma sample

- Makefile
Since we seem to hit the LLD hang with every single CI run now, I did some investigating on a Windows 10 VM. I was able to reproduce the issue in 100% of all attempts and found out that it is related to LLD using multi-threaded linking by default, and that we can work around the issue by disabling that.
This is an issue that has been encountered by others [before](https://github.com/android/ndk/issues/855) and was [seemingly fixed](https://reviews.llvm.org/D53968) but seems to have returned in some other form.
Since, according to reports in Discord, this problem doesn't always happen, I tested this patch by building the recently merged gamma sample ten times with and ten times without the patch. Without it, it always hung, with it, it always worked.
Fixes #279.
> build: Fix LLD hang on Windows by disabling multi-threaded linking

- .github/workflows/build_samples.yml
The recent linker hangs on Windows made me realize that GH Actions have a default timeout of six hours, which is unnecessarily large for our purposes. This sets a custom timeout of 20 minutes, which is far less wasteful, but still is 4-5x the time required by our slowest build job, so we don't risk running into that limit soon.
> ci: Set a 20 minute job timeout

- Makefile
The current code only works on x86_64. The proposed patch adds support for i686.
cgc: version 3.1.0013, build date Apr 18 2012 13:43:10.
> build: Add support for 32 bits build environment

- lib/hal/fileio.c
- lib/winapi/fiber.c
- lib/xboxrt/libc_extensions/stdlib_ext_.c
Based on the [Discord discussion](https://discordapp.com/channels/428359196719972353/428360618102226946/664534847082987563) I went through `hal`, `nxdk`, `xboxrt` and `winapi` to check for variables or functions that could be static but aren't, and fixed every occurrence I found. Depending on whether we build the code as a library I used `nm --defined only` on the library file or read through the sourcecode.
> Make non-public functions and variables static

- lib/xboxrt/libc_extensions/malloc.h
I'm not a huge fan of `alloca`, but some code out there (like libraries used by SDLPoP) use it, and it's an easy thing to add. Some test code can be found [here](https://gist.github.com/thrimbor/2815f00a97966b97028ac0a23b94bde3), it mainly checks whether we corrupt the stack.
> libc: Add alloca() / _alloca()

- lib/xboxrt/libc_extensions/malloc.h
As @JayFoxRox pointed out `alloca()` isn't allowed to be a static function because the memory allocated is in the local stackframe and will be invalid after returning.
> libc: Fix alloca()

- lib/xboxkrnl/xboxdef.h
This exposes these types through windef.h (which primarily includes xboxdef.h).
This is necessary for https://github.com/XboxDev/nxdk-sdl/pull/24#discussion_r366668605.
I wasn't sure wether I should add these types to windef.h directly as they aren't used in the kernel (yet?).
I decided for xboxdef.h because our windef.h is really slim right now. Also our xboxdef.h already has `DWORD_PTR` which isn't used in the kernel either (also, that one should actually be in BaseTsd.h instead, so we have to refactor in the future anyway). 
You can find the documentation for these types here: https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types
*(Random note: Our windef.h should probably also be renamed to WinDef.h in the future, to deal with case-sensitivity)*
> winapi: Add INT / PINT / LPINT / UINT / PUINT / LPUINT types

- lib/pbkit/pbkit.c
Closes #41.
See https://github.com/XboxDev/nxdk/issues/41#issuecomment-570888513 for my theory as to why that is.
This was debugged using https://github.com/JayFoxRox/nxdk/pull/65.
There are actually a handful of registers which should probably be set, but aren't. I only focused on those which "scared" me the most. So this is merely a quick-fix for the worst offenders. I have written  #271 so we can do a more extensive refactor in the future.
> Improve `pb_init`

- samples/gamma-fade/Makefile
- samples/gamma-fade/README.md
- samples/gamma-fade/main.c
- samples/gamma/main.c
This adds another gamma sample which shows how to abuse the gamma ramps for fade-effects.
This was written independently from #265 (before review had finished) but I tried to adapt the requested style changes.
The README.md needs someone to spell-check.
The image is as unsuitable as the one in #265. I might improve it in the future maybe.
I already have a prototype for loading BMPs with SDL (in https://github.com/JayFoxRox/nxdk/pull/66), but that has some drawbacks, too (so I'm not going to submit it).
> samples: Add gamma-fade sample

- lib/xboxkrnl/xboxkrnl.h
* `KeRestoreFloatingPointState` was not marked as `NTAPI` and wasn't linkable (as name decoration in import lib is different). I ran into this, because a future submodule PR of mine will use a DPC which might require the FPU.
* `HalBootSMCVideoMode` is a variable, not a function. I found this using: `grep XBAPI -R ./ | grep -v FASTCALL | grep -v NTAPI | grep -v CDECL | grep \(`.
> Fix some xboxkrnl prototypes

- lib/hal/audio.c
OpenXDK XAudio actually contains some code that probably doesn't conform with AC97.
It still works on hardware, but it doesn't work in XQEMU.
This PR fixes that, so that audio works in XQEMU.
I also have an explanation and a patch for XQEMU in https://github.com/JayFoxRox/xqemu/pull/41 (including reasons as to why I don't intend to upstream it).
The primary motivation for this change is to make it more standard, and also to make it easier to test in XQEMU.
**I have not tested this patch on hardware yet.**
> Fix OpenXDK XAudio in XQEMU

- lib/net/Makefile
- lib/net/nforceif/include/lwipopts.h
- lib/net/pktdrv/pktdrv.h
This fixes some issues that occur when using lwip from C++, such as missing include paths, name mangling, and issues with including `errno.h.` (which was encountered by @dracc).
Mostly tested by building one of the http server samples as C++ code, and @dracc's ftpserver-branch of NevolutionX.
Closes #296.
> lwip C++ compat fixes

- lib/hal/audio.c
OpenXDK XAudio code currently doesn't work on debug BIOSes, due to triggering an assertion in `MmGetPhysicalAddress()` when calling `XAudioInit`. Without attaching a debugger, this looks like a hang, but it actually is a check whether the pages are locked in memory (which they should be for MMIO/DMA). This commit fixes it by manually locking the pages before calling that function.
There are other, less obvious, issues with that code though. The memory for the descriptors is part of `ac97Device`, which resides in `.data`. One day someone may get unlucky and have a descriptor entry cross a page-boundary with those two pages not being contiguous, and crazy things will happen.
> audio: Fix MmGetPhysicalAddress() assertion on debug BIOS

- lib/hal/xbox.h
- lib/net/nforceif/src/sys_arch.c
This marks `XCreateThread` as deprecated and replaces its use in the network code with `CreateThread`. Tested on my Xbox with the httpd servers.
> Deprecate and remove uses of XCreateThread

- lib/winapi/fileapi.h
- lib/winapi/filemanip.c
This implements `GetDiskFreeSpaceExA()` and `GetDiskFreeSpaceA()`.
I checked the results of both functions against the values reported by the dashboard on my Xbox, and they do match. The error reporting (both `SetLastError(ERROR_PATH_NOT_FOUND);` and returning `0xFFFFFFFF` in `GetDiskFreeSpaceA()`) were checked against the behavior of Windows 7.
> Implement GetDiskFreeSpaceExA() / GetDiskFreeSpaceA()

- .gitmodules
This changes the submodule URL for lwIP from `git://git.savannah.nongnu.org/lwip.git`, their normal repo, to `https://github.com/lwip-tcpip/lwip.git`, their GitHub mirror, which they also use for CI.
The main reason for this is to allow shallow cloning, which doesn't work with their regular repo. It also has the benefit of GitHub allowing you to browse the submodule repo at the version used in nxdk by simply clicking on the submodule folder in the nxdk repo.
To update the local submodule remote URL one needs to run `git submodule sync`.
> lwip: Change submodule URL to GitHub mirror

- lib/xboxkrnl/xboxkrnl.h
I encountered this today when experimenting with using an APC to handle packet reception, where I got weird return value issues because the calling convention of my APC routine (which followed the kernel headers) was wrong.
I tested the changes to the APC-routines, and checked the other prototypes against ReactOS where possible.
> xboxkrnl: Fix calling convention of all callbacks

- Makefile
Just a little thing I noticed when I was investigating optimization options - we're currently using `/dll` in order to get a PE file with a `.reloc` section, but we can have that by just using `/fixed:no`, which has the benefit of not generating an unnecessary import lib (which may confuse people).
I tested the change, and everything still seems to work fine.
> build: Use /fixed:no instead of /dll

- lib/xboxkrnl/xboxkrnl.h
Since #229 was merged, I've done a bit more reading on the volatile keyword and how it might impact our use-case (such as [this](https://docs.microsoft.com/en-us/cpp/cpp/volatile-cpp?redirectedfrom=MSDN&view=vs-2019), [this](https://docs.microsoft.com/en-us/cpp/cpp/const-and-volatile-pointers?view=vs-2019) and a couple of more random stuff).
Since we're using exported kernel symbols, clang cannot assume that pointers or values retrieved from the kernel or passed to kernel functions won't change during kernel calls. This is not explicitly documented somewhere, but not having this guarantee would completely break DLLs (or even normal linking), so I think this is safe to assume. That means we only have to worry about kernel data that could change during execution of XBE code, such as …
> xboxkrnl: Remove "volatile" keyword from declarations not requiring it

- .github/workflows/build_samples.yml
This changes the GH workflow to do shallow clones of git repos, which reduces the amount of traffic we cause on the build VM and the cloning time a bit.
> ci: Use shallow cloning

- README.md
This PR fixes a outdated link to the pbkit in the README.md by replacing the old link with a saved version from archive.org
> docs: Update pbkit link on README.md

- lib/xboxrt/c_runtime/_fltused.c
For some reason `_fltused` seems to get dropped somewhere when using LTO, even though it's implicitly referenced. I'm not sure what exactly causes this, and whether this is expected with this special symbol, or a bug in clang, or lld...
Adding a linker pragma fixes this, though. It should only be added when the obj file is pulled in, so it should be fine to have it there.
> xboxrt: Fix lld dropping the _fltused symbol when using LTO

- lib/xboxrt/libc_extensions/string_ext_.c
- lib/xboxrt/libc_extensions/string_ext_.h
This adds `_stricmp`, `stricmp`, `_strnicmp` and `strnicmp` as libc extensions. This hopefully eliminates the need for some workarounds, such as in @Ryzee119's SDLPoP port.
The code is copied from PDCLib's normal comparison functions, but adjusted to behave like the MSDN describes. The only difference is that it doesn't invoke an invalid parameter handler routine when encountering a null pointer, instead it behaves as if the invalid parameter handler routine allowed to continue execution. I added asserts to still catch those errors in debug builds.
Interestingly, ReactOS's version of these functions does not do that at all, and also uses `toupper` instead of `tolower` (the latter being what the MSDN describes).
> libc: Implement case-insensitive string comparison functions

- lib/Makefile
- lib/winapi/Makefile
- lib/xboxrt/Makefile
For using CMake or other build systems, it is more suitable to have these "modules" as actual libraries.
> Build winapi and xboxrt as libraries

- samples/hello/main.c
- samples/httpd_bsd/httpserver.c
- samples/sdl_ttf/main.c
This makes the spelling of "nxdk" a bit more consistent.
We have been going back and forth with "NXDK" and "nxdk", but most instances are "nxdk" (in lowercase) now.
Some instances of uppercase spellings might still exist in code comments / submodules. We can fix those later / when we touch such code.
`NXDK` remains a preprocessor macro for finding out if compilation is happening with nxdk.
> Spell "nxdk" in lowercase

- lib/xboxrt/libc_extensions/tchar.h
This adds `tchar.h`, as a preparation to reduce the diff to upstream for the next PDCLib rebase (it's included by dlmalloc).
PDCLib actually builds fine with an empty header, but I decided to provide at least some functionality. I'm not too worried about it being complete or correct - it's not very likely that we'll encounter code that requires it, so I consider it to be more of a bonus that we can improve when required.
> libc: Provide tchar.h

- lib/xboxrt/libc_extensions/stdlib_ext_.h
Pulled from my OpenAL-soft port; but maybe also required elsewhere.
> xboxrt: Add Microsoft __min and __max macros

- lib/winapi/Makefile
- lib/winapi/badptr.c
- lib/winapi/basetsd.h
- lib/winapi/winbase.h
Pulled from my OpenAL-soft port; but maybe also required elsewhere.
This is a very weird function, which seems to probe page access rights (similar to `VirtualQuery` or `VirtualProtect`?). I'm not sure how this is implemented on Windows or how we should implement this on Xbox (also think of physical vs. virtual memory APIs on Xbox).
OpenAL seems to use it to check if enough elements in an array exist before trying to resize it.
I decided to stub it for now (and start upstreaming my changes as soon as possible, so they don't pile up). I might have to revisit / implement it in the near future, as I begin testing the port.
I wasn't sure about calling the file BaseTsd.h or basetsd.h - MSDN usually calls it BaseTsd.h, and due to case sensitivity, I decided to go with that.
The implementation …
> winapi: Stub IsBadWritePtr

- lib/winapi/sync.c
- lib/winapi/synchapi.h
Pulled from my OpenAL-soft port; but maybe also required elsewhere.
This adds the `WaitForSingleObject` function (simply forwarding to the existing `WaitForSingleObjectEx`).
I also decided to add `WaitForMultipleObjects` and `WaitForMultipleObjectsEx` (based on the existing `WaitForSingleObjectEx`).
None of this code was tested. I assume it works fine. If there are bugs, they likely already existed in the existing `WaitForMultipleObjects` functions or our xboxkrnl header.
> Implement more WaitFor* functions for winapi

- lib/xboxrt/libc_extensions/crtdbg.h
This stubs the _ASSERT macros. See MSDN: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/assert-asserte-assert-expr-macros?view=vs-2019
This file is included by newton-dynamics. It uses at least one of these macros (I forgot which one, and added all 3 for completeness).
The implementation is very naive and does not follow the description in the MSDN. I consider this a stub for now.
> libc: Stub Microsoft _ASSERT macros in crtdbg.h

- lib/xboxrt/libc_extensions/direct.h
This can probably reuse code we'll eventually implement for unistd.h: https://en.wikipedia.org/wiki/Direct.h
newton-dynamic includes this file, but doesn't actually use it. Hence an empty file.
Because the name is vague I decided to leave a comment (this is different from the unistd.h which is completely empty, with no hint about it implementing UNIX / POSIX).
> libc: Stub Microsoft direct.h

- lib/net/nforceif/include/lwipopts.h
AUTOIP has different names, but it is:
- [IETF: RFC 3927](https://tools.ietf.org/html/rfc3927)
- [Microsoft: APIPA](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc958957(v=technet.10)?redirectedfrom=MSDN)
- [Wikipedia: Link-local address](https://en.wikipedia.org/wiki/Link-local_address)
I'd like to have it, because it allows zero-config system-link-like architecture without a central DHCP server and without static IP configurations.
---
Applications should be able to use it similar to DHCP, like this (untested code):
```c
#ifdef DHCP
#include <lwip/dhcp.h>
#else
#include <lwip/autoip.h>
#endif
```
```c
#ifdef DHCP
dhcp_start(g_pnetif);
#else
autoip_start(g_pnetif);
#endif
```
```c
#ifdef DHCP
debugPrint("Waiting for IP (DHCP)...\n");
while …
```
> lwip: Enable AUTOIP module

- lib/Makefile
- lib/net/Makefile
- samples/gamma-fade/Makefile
- samples/gamma/Makefile
- samples/hello/Makefile
- samples/httpd/Makefile
- samples/httpd_bsd/Makefile
- samples/led/Makefile
- samples/mesh/Makefile
- samples/sdl/Makefile
- samples/sdl_image/Makefile
- samples/sdl_ttf/Makefile
- samples/triangle/Makefile
- samples/xaudio/Makefile
- tools/cxbe/Makefile
- tools/fp20compiler/Makefile
- tools/vp20compiler/Makefile
Hi,
closes #67
I replaced all wildcards in all Makefiles I could find. There are still wildcards in these sub-repositories:
- `lib/zlib`
- `lib/pdcib`
- `lib/sdl`
- `lib/net/lwip`
> build: Replacing wildcards with paths

- lib/winapi/Makefile
- lib/winapi/shlobj.h
- lib/winapi/shlobj_core.c
- lib/winapi/shlobj_core.h
- lib/winapi/windef.h
Pulled from my OpenAL-soft port; but maybe also required elsewhere.
This adds a stub for `SHGetSpecialFolderPathA` which will always fail on Xbox (at least for now).
I also added CSIDL_APPDATA as I found it in mingw source-code (they keep it in shfolder.h), because that's required for OpenAL-soft.
Normally this function is supposed to return a common path (like the users document folder), so a potential implementation would return UDATA / TDATA in the future (it's still a bad fit).
I tried to keep the filenames as named in MSDN - I don't have a Windows SDK to check if this is right.
> winapi: Stub SHGetSpecialFolderPathA

- lib/winapi/Makefile
- lib/winapi/libloaderapi.c
- lib/winapi/libloaderapi.h
- lib/winapi/windef.h
- lib/winapi/windows.h
Pulled from my newton-dynamics port.
For now, it's just to make it easier to compile libraries or applications. Most applications will handle failure of `LoadLibrary` very gracefully (typically it's used for optional plugins).
Entirely untested at runtime, but tested compilation with:
```c
HMODULE* dll = LoadLibrary("sample.dll");
if (dll != NULL) {
void* f = GetProcAddress(dll, "sample_function");
FreeLibrary(dll);
}
```
I might implement a linker in the future (if nobody beats me to it).
> winapi: Stub parts of dynamic-linker API

- lib/hal/video.c
This hopefully closes #343. However, this code is untested and I have not tried to reproduce the problem.
- On PAL Xboxes, the users get to enable/disable PAL-60.
- On NTSC Xboxes, the users get to enable/disable 480p, 720p and 1080i.
However, nxdk code in master *always* looks at the PAL-60 setting, regardless of the video standard. It also always looks at the HD modes, regardless of video standard.
I'm not sure if the MS dashboards defaults to a safe value for PAL-60 (for NTSC), or safe values for 480p, 720p and 1080p (for PAL) if the video-standard does not have those settings.
This, potentially, causes trouble:
- On a PAL Xbox, we might accidentally reject all 480 line modes. PAL only has 480i (and no 480p), but if the NTSC 480p setting is turned on, we try to force 480p by rejecting …
> video: Respect video-region when querying dashboard settings

- lib/winapi/Makefile
- lib/winapi/winmm/Makefile
- lib/winapi/winmm/mmsystem.h
- lib/winapi/winmm/timeapi.c
- lib/winapi/winmm/timeapi.h
This adds a stub for the most critical functions of Winmm.lib: `timeGetTime` and the period functions. This is built a separate library as this is likely where winapi will be heading.
~~I used "Winmm" instead of "winmm" because that's what MSDN often did. However, I'm already aware of projects linking against lowercase "winmm.lib". I'm not sure how to deal with this on case sensitive filesystems.~~ I'm now following MinGW style of all-lowercase.
I'm not sure how exactly the period functions should interact with the rest (if setting a high value as period will also reduce granularity of `timeGetTime`?). I'm also not sure if `timeBeginPeriod` and `timeEndPeriod` work like a stack.
For now, the `timeGetTime` will always run in milliseconds, and the period functions will always claim success. …
> winapi: Stub parts of Winmm.lib

- .github/workflows/build_samples.yml
Our Windows CI recently started failing. The issue came down to a path conflict - the newer images contain an msys2 installation in `C:\msys2`, which is also where our own msys2 installation got extracted to. Partially overwriting the pre-existing installation then caused weird issues when trying to update or install packages.
This fixes it by changing the path where we extract msys2 to `C:\tools\msys2`, which is the path where chocolatey normally puts it (this path is also used in xqemu). Since we don't use chocolatey here to install msys2, there should be no path conflicts.
> ci: Fix path conflict with preinstalled msys2

- Makefile
- lib/xboxrt/c_runtime/_fltused.c
This fixes lld crashes with LLVM 10 (and maybe more versions) when using LTO. The crash is caused by issues in lld with regards to handling of symbols that get emitted during code generation, in this case, `__fltused` and `__chkstk`/`__xlibc_check_stack`. I've opened a bug report upstream for this: https://bugs.llvm.org/show_bug.cgi?id=45985
The solution in this PR is to add linker parameters that make lld add the symbols properly. I would prefer a cleaner solution, but this will probably require waiting for a future LLVM release. In the meantime, this makes it possible to build SDLPoPX with LTO turned on.
> build: Work around LLVM LTO symbol issues

- samples/sdl_ttf/main.c
Changes in pdclib:
- xbox: Switch to using winapi for file I/O
- Implement gmtime()
The second change (gmtime) is just a minor one. I assume there won't be any issues.
The first change (winapi file I/O) is more critical and it's a breaking change. Existing apps will have to be reworked to use absolute paths and backslash instead forward-slash. The same path limitation exists with XDK, but it did not previously exist in nxdk / OpenXDK. Such limitations also do not exist on Windows.
You must also manually mount partitions that you plan to use. "D:" is typically auto-mounted as the current XBE path or DVD drive (depending on who mounts it). No other partitions are mounted by default.
We are considering to bring this closer to Windows, but it will take a lot more time. So please update your …
> pdclib: Update submodule to 31473f1

- samples/hello++/Makefile
- samples/hello++/main.cpp
This addresses #311 by enabling `NXDK_CXX = y` in the hello++ `Makefile`
> samples: Enable C++ support for hello++

- lib/hal/audio.c
- lib/hal/audio.h
**This code was tested very little; in particular, I did not test it with any existing OpenXDK XAudio applications. I also did not test the digital audio-out.**
Please test and review before merge. For testing, I've been using https://github.com/JayFoxRox/nxdk/pull/78 which can create some metadata for audacity.
---
The interrupts for analog audio come about 16 samples before digital audio interrupts. This means we might mark a buffer as processed (by calling the user callback) before the AC97 has finished processing it.
We also cleared the interrupts for the digital audio in the interrupt handler of analog audio. This could lead to race conditions.
This commit keeps counters so we always know how many buffers there are per bus master.
Only once both bus masters have processed the buffer, …
> Fix many issues in OpenXDK XAudio

- tools/cxbe/Makefile.am
Hi 👋 
This PR has no dedicated issue.
It removes the file `Makefile.am` from `tools/cxbe/` as it is needless. 
I build a few samples without issue.
> cxbe: Remove obsolete Makefile.am

- samples/mesh/main.c
- tools/vp20compiler/config.h
- tools/vp20compiler/main.c
- tools/vp20compiler/nvvertparse.c
- tools/vp20compiler/nvvertparse.h
This PR is best reviewed one commit at a time:
See https://www.khronos.org/registry/OpenGL/extensions/NV/NV_vertex_program.txt for more background information.
The register indices for registers of the same semantics of NV2A and NV_vertex_program differ.
When we support the fixed-function-pipeline or certain immediate-mode setters in the GPU, where we can't just remap the vertex attributes, this will be a problem.
To solve this, this commit creates an array with the hardware registers. These must match the names of the NV_vertex_program registers, but be in hardware order.
The parser will check if the used NV_vertex_program registers exist in hardware. If the index is different, it warns (to avoid people assuming a 1:1 mapping and using indices from the NV_vertex_program spec on the CPU …
> vp20compiler: Various improvements and better support for NV2A

- lib/hal/debug.c
- lib/hal/debug.h
Hi 👋 
This PR
- removes unused color constants from `debug.h`
- renames `advanceScreen()` to `debugAdvanceScreen()` to mind the namespace
Aims to close #171 
Samples still compile and a quick search revealed that `advanceScreen()` is no where in use inside nxdk.
> hal: Remove dead constants and adjust function name prefix

- tools/fp20compiler/rc1.0_register.h
Hello 👋 
This PR closes #236 
It does so, as suggested, by replacing the return value with an `assert(false);`. 
I wasn't sure if I should also add a warning `fprintf` or not. Feel free to request it 🙂
> fp20compiler:  Replace bad emitter string for REG_ONE with assert(false)

- samples/gamma-fade/Makefile
- samples/gamma/Makefile
- samples/hello++/Makefile
- samples/hello/Makefile
- samples/httpd/Makefile
- samples/httpd_bsd/Makefile
- samples/led/Makefile
- samples/winapi_drivelist/Makefile
Hi! 👋 
I spotted that the assignment style for various flags(mainly `XBE_TITLE`) in the Makefiles is irregular. This PR harmonise it by making sure there is always exactly one whitespace before and exactly one whitespace after a given `=`. 
I rebuild all samples without an issue. I did not run them.
> samples: Harmonise flag assignment style in Makefiles

- lib/winapi/minwinbase.h
- lib/winapi/processthreadsapi.h
- lib/winapi/thread.c
This implements `GetExitCodeThread()`, which is required by my upcoming PDCLib PR that will simplify the C11 threading code by implementing it on top of the Win32 thread API. The implementation is roughly based on the code in `thrd_join()`.
Quick testcase:
```c
DWORD WINAPI threadFunc (LPVOID lpParam) {
return 0xDEADBEEF;
}
int main(void)
{
HANDLE t = CreateThread(NULL, 0, threadFunc, NULL, 0, NULL);
Sleep(2000);
DWORD exitcode;
GetExitCodeThread(t, &exitcode);
debugPrint("ec: %x\n", exitcode);
while(1) {
Sleep(2000);
}
return 0;
}
```
> winapi: Implement GetExitCodeThread()

- Makefile
- lib/xboxrt/Makefile
- lib/xboxrt/vcruntime/threadsafe_statics.c
The C++11 standard requires statics-initialization to be thread-safe. We had this behavior disabled till now, since we lacked the code to support the way MSVC (and clang when building for Windows) implemented it.
This code adds support for this and removes the compiler parameter that disabled it. The code is derived from and mostly identical to the one in the ReactOS CRT, but it contains two notable fixes, which I figured out by doing a bit of RE:
* `_Init_global_epoch` and `_Init_thread_epoch` get their correct starting values
* `_Init_thread_epoch` gets properly updated, so `_Init_thread_header` only gets called once per thread after initialization is done (clang automatically generates code that checks the epoch values)
I have some terrible code …
> vcruntime: Implement thread-safe statics initialization

- lib/hal/xbox.c
- lib/hal/xbox.h
This removes `XGetTickCount`, `XSleep` and `XCreateThread`, all of which have been marked as deprecated before and been replaced by their winapi counterpart.
Suggested migration path for third parties:
`XGetTickCount` -> `GetTickCount`
`XSleep` -> `Sleep`
`XCreateThread` -> `CreateThread`, or, in special cases and when you know exactly what you are doing, `PsCreateSystemThreadEx`
> hal: Remove deprecated functionality from xbox.c

- Makefile
While experimenting with intercepting the debug output, I noticed that no debug info was generated for assembly files. This fixes it by adding the flag to generate DWARF debug info to the assembler flags when debug info is requested.
> build: Add DWARF debug info to the assembler flags, too

- lib/pbkit/pbkit.c
This fixes the GPU initialization issue encountered when enabling compiler optimizations, as described in #291, by applying the `volatile` keyword at the places described in the issue. I'm aware that there are potentially a lot more of these problems in the code, however, fixing all instances will take a more in-depth revision of the entire code. This is only meant to ensure that the recent interest in utilizing the GPU doesn't hit this problem.
Fixes #291.
> pbkit: Fix compiler optimizations breaking GPU initialization

- lib/xboxrt/libc_extensions/stdlib_ext_.h
- lib/xboxrt/libc_extensions/string_ext_.h
About two hours ago lorecast162 mentioned issues in Discord with using `std::abs` with a parameter of type `std::intmax_t`. We tracked it down to libc++ expecting the C standard library to provide the `abs` overloads for `long` and `long long` when building C++ code.
I went through libc++'s `math.h` and added all expected overloaded functions to our PDCLib extension header for `stdlib.h` (which is the header libc++ expects to find these functions in). The overloarded functions added are basically identical to the ones libc++ provides for other platforms.
I then searched for other occurrences of this, and found similar issues in `string.h`. `_NXDK_PREFERRED_OVERLOAD` is necessary because otherwise the compiler doesn't allow overloading these functions as only the return type differs for …
> libc: Provide math.h / string.h overloads expected by libc++

- Makefile
- lib/xboxrt/Makefile
- lib/xboxrt/vcruntime/vcruntime_typeinfo.cpp
- lib/xboxrt/vcruntime/vcruntime_typeinfo.h
This fixes the `lld: error: undefined symbol: const type_info::'vftable'` linker error that would usually appear when enabling RTTI and linking a program that instantiates a class containing virtual methods, and enables RTTI. This is enough to give it a quick test:
```
class A {
public:
virtual ~A() {};
};
A a;
```
This is achieved by the following changes:
* Build the `type_info` class with `-fno-rtti` to prevent it from emitting a recursive reference to its vftable
* Implement the empty virtual destructor which acts as the key function
* Add a hidden constructor, because LLVM will optimize away the vftable if the class is not instantiable.
Removing `const` in `__std_type_info_data` is not necessary to get this working, but is required for when we eventually implement name demangling, …
> vcruntime: Fix and enable RTTI

- lib/xboxkrnl/xboxkrnl.h
This fixes a warning about implicitly casting away `const` in `WaitForMultipleObjectsEx`.
From what I could see, `NtWaitForMultipleObjectsEx` doesn't try to modify the handles array (it also wouldn't make any sense), so we should be fine.
> xboxkrnl: Make Handles parameter of NtWaitForMultipleObjectsEx const

- tools/fp20compiler/ts1.0_inst_list.cpp
This adds most of the missing texture modes into fp20compiler, except for BRDF and rectangle modes, which can be added at a later date.
Futhermore, some modes which take additional arguments (e.g. `offset_2d(tex, float, float, float, float)`) will now be processed, and the compiler will emit pbkit code to set the appropriate GPU registers as required.
This makes some progress on #208.
> fp20compiler: Add more missing texture modes and process texture mode arguments

- lib/hal/debug.c
- lib/hal/video.c
- lib/hal/video.h
This supersedes #355.
The commits are mostly the same - I only addressed the review comments from #355 and modified the newly introduced functions to use `(void)` instead of an empty parameter list.
I tested the changes by running the samples as well as a slightly modified (to remove the `_fb` reference in it) SDLPoPX.
Closes #170.
Closes #169.
Closes #149.
Closes #269.
> Allocate framebuffer when XVideoSetMode is called

- samples/sdl/main.c
- samples/sdl_image/main.c
- samples/sdl_ttf/main.c
b8d162b0aa9f5da5ed7a2af0cd7fb084a394ad89 changed the default values of SCREEN_WIDTH	and SCREEN_HEIGHT to zero. 
Now these are only synchronised to the actual framebuffer size when using the debug API.
Unfortunately this broke the sdl, sdl_tff and sdl_image samples as they relied on using these variables by `extern int`. 
This fix declares them locally in each sample.
Not sure if this is the best solution going forward, but it gets the samples working again.
Issue reported on xboxdev discord by a user.
> samples: Fix extern screen variables

- lib/nxdk/path.h
I stumbled upon this issue while trying to make NevolutionX expose the DVD drive as "D:".
> nxdk: Add extern "C" identifier in path.h

- tools/cxbe/Xbe.cpp
This makes cxbe spit out warnings on excessive image sizes, to better diagnose issues such as #324.
> cxbe: Warn on excessively large image sizes

- README.md
> readme: Remove reference to non-existent lib/xlibc-rt

- lib/hal/debug.c
- lib/hal/debug.h
This makes it easy to use debugPrint() to make a simple persistent readout. Call debugPrint() with your readout text after you have drawn your screen, then debugResetCursor() to prevent the next frames prints from running down the screen on the next frames.
It's not perfect because the readout will flicker a bit depending on how fast the screen is being updated, but it's very easy to use this way and perfectly readable for quick debug output.
> debug: Support setting and resetting cursor position

- Makefile
This changes the linker parameters to directly link to the fixed base `0x00010000` instead of producing a relocatable binary that is then relocated by cxbe. I did this mainly to make debugging a bit more comfortable - with the exe already having the correct base, we can just let gdb read it directly without having to extract section addresses from the xbe.
Another benefit is that it reduces binary size by not emitting a `.reloc` section.
> build: Link to fixed base instead of relocating in cxbe

- .dockerignore
- .github/workflows/build_docker_image.yml
- .github/workflows/build_samples.yml
- Dockerfile
This adds a Dockerfile plus two actions to build and test a Docker image containing Alpine Linux 3.12, the requirements of nxdk (llvm etc.) and the nxdk source code. Pushes to master will trigger the second action, which builds the image and pushes it to DockerHub: https://hub.docker.com/repository/docker/xboxdev/nxdk. The images are tagged with their git short hash, so we we can correlate commits and images.
I also added a `.dockerignore` to exclude the git directories and some other large unnecessary directories and files from the image to reduce the size.
For the push to DockerHub to work, we'll have to configure the username and token secrets on the nxdk repo before merging.
To test, you can pull the image from https://hub.docker.com/repository/docker/thrimbor/nxdk and run this from a …
> ci: Build, test and push Docker image

- lib/winapi/memory.c
- lib/winapi/winbase.h
This adds `ZeroMemory`, which is just a wrapper for `RtlZeroMemory`. I initially used this in a feature branch I'm working on, and even though that branch now doesn't require it anymore, I still think it's worthy of getting added just for completeness.
> winapi: Implement ZeroMemory()

- .github/workflows/build_docker_image.yml
This restricts the Docker image building workflow to only run for the XboxDev nxdk repo. Without this condition, it will also try to run when downstream repos update their master branch, and fail (or cause a mess when the owner has XboxDev access).
I tested on my own repo that it works and will still trigger for the XboxDev nxdk repo.
> ci: Only push Docker image when running on main repo

- .editorconfig
- Makefile
This removes stray whitespaces, and introduces a .editorconfig file to avoid re-introducing them.
> Clean up stray whitespaces in Makefile, add .editorconfig

- Makefile
Argument expects an integer on the latest version of lld-link (11.0.0-1), rather than the string "no".
This fixes compilation of nxdk programs on windows msys2, which would otherwise have shown the following error at link time:
`lld-link: error: -threads:: expected a positive integer, but got 'no'`
Tested and working also with clang/llvm 9, for compatibility. It just shows up as an unknown argument warning anyway.
> Makefile: Fix lld-link -threads argument

- lib/xboxkrnl/xboxkrnl.h
The documentation for OBJECT_ATTRIBUTES's ObjectName was wrongfully stating that it's a Unicode string, while it is actually an ANSI string.
Also documented a few more functions that I used in another commit today.
> xboxkrnl: Document string and event functions, fix OBJECT_ATTRIBUTES doc

- .github/workflows/build_samples.yml
GitHub is currently rolling out a change that makes ubuntu-latest equivalent to ubuntu-20.04 instead of 18.04. On Ubuntu 20.04, the llvm package doesn't seem to be installed out of the box, so for users already affected by the change, Ubuntu CI currently fails.
This commit fixes that by explicitly installing llvm.
> ci: Explicitly install llvm package to get llvm-lib

- samples/winapi_filefind/Makefile
Follow up of PR #371 
This one Makefile got away without being fixed. Whoops! 😬
> samples: Fix style consistency in Makefile of winapi_filefind

- Makefile
- samples/gamma-fade/Makefile
- samples/gamma/Makefile
- samples/hello++/Makefile
- samples/hello/Makefile
- samples/httpd/Makefile
- samples/httpd_bsd/Makefile
- samples/led/Makefile
- samples/mesh/Makefile
- samples/sdl/Makefile
- samples/sdl_gamecontroller/Makefile
- samples/sdl_image/Makefile
- samples/sdl_ttf/Makefile
- samples/triangle/Makefile
- samples/winapi_drivelist/Makefile
- samples/winapi_filefind/Makefile
- samples/xaudio/Makefile
On a side note, as I mentioned in the related issue, XBE_TITLE requires just quotation marks to use spaces and special characters, but GEN_XISO requires quotation marks *and* the \ escape character, thus I wasn't able to make GEN_XISO use the XBE_TITLE. Theoretically, it should have been possible to use \ in XBE_TITLE, but, when used, a simple hex view of the xbe shows that \ is also written to the XBE's title, and doesn't actually escape anything.
The samples have also been tested to load and run fine with this fix, so it should cause no issues.
If anyone has a way to fix this or a better way to do the naming, I'll gladly accept it.
Closes #372.
> samples: Change titles

- lib/hal/debug.c
Currently when printing a hex value using `debugPrintHex` with a sign bit, it would print the 32bit two's complement hex version
i.e printing `0x80` would print `0xffffff80`
Before:
After:
> debug: Ensure unsigned char when printing hex bytes

- Makefile
- lib/winapi/libloaderapi.c
- lib/winapi/winnt.h
- lib/xboxkrnl/xboxdef.h
- lib/xboxkrnl/xboxkrnl.h
This grew a bit larger than anticipated. It implements the ability to look up functions marked with `__declspec(dllexport)` by calling `GetProcAddress` with NULL as the handle. JFR and I briefly talked about this in #335, but we wrongfully assumed that this would look up the exports of the module calling `GetProcAddress`, while it actually looks up the exports of the main module, i.e. the currently running xbe in this case. I have confirmed that this is the correct behavior by testing on Windows 7 with VS 2017.
8df5cb2 is required to be able to do this at all. To look up exports, we need the `IMAGE_EXPORT_DIRECTORY` header. This header is referenced in the PE optional header, but the xbe format does not have such a reference. The struct gets its own section called `.edata`, but modern …
> Implement lookup of functions export by the xbe, add PE and XBE header structs

- lib/winapi/thread.c
This is a small and simple change - `CreateThread` so far directly used a memory address to get the stack size field from the XBE header, but since we now have proper structs and the `CURRENT_XBE_HEADER` macro to provide safer access, we can use that instead.
> winapi: Use XBE header struct when getting default stack size for thread

- Makefile
This removes the `NXDK_STACKSIZE` variable in the Makefile. Overriding the nxdk default stack size is still possible by simply appending another `-stack:` parameter to the linker flags.
> build: Remove NXDK_STACKSIZE variable

- Makefile
This makes it so that dependency files (`.c.d`) derive their path from the object file that gets created instead of the source files. For nxdk, this makes no difference, but for the ports repo I'm working on, it makes it possible to have an out-of-tree build.
> build: Create dependency file path from obj path instead of source path

- lib/xboxrt/libc_extensions/stdlib_ext_.c
- lib/xboxrt/libc_extensions/stdlib_ext_.h
This implements `_byteswap_ushort`, `_byteswap_ulong` and `_byteswap_uint64`, as they're required by zstd. #418 also implemented them, but this PR implements them as normal functions, which is the way MS does it in their crt.
Also, as laid out in the Discord, I plan to create a new repo for library ports, and put zstd there instead.
> libc: Add Win32 byteswapping functions

- lib/xboxrt/c_runtime/check_stack.c
Fixes #359.
Previously, we just resumed execution when a stack overflow was detected. In my testing, the subsequent use of the stack would then trigger a stack overflow exception in the kernel and execution would halt, but it's not good to rely on that behavior.
This commit adds an explicit throw of an `EXCEPTION_STACK_OVERFLOW` exception, which will immediately cause the kernel to walk the handler chain in search of a handler for the exception. If no handler is found, execution is halted by the kernel automatically, but a debugger still has a chance to intercept this.
> xboxrt: Throw exception on stack overflow

- lib/xboxrt/Makefile
- lib/xboxrt/vcruntime/stack_protection.c
This implements stack smashing detection support. When stack protection is enabled, this will catch attempts to overwrite the return address on the stack by overflowing stack buffers.
At the moment, a static default value is used as the canary value, but a call to `__security_init_cookie()` will be added to PDCLib soon.
To test, add the `-fstack-protector-all` clang parameter and try the following code:
```c
void tfunc ()
{
char buf[3];
memcpy(buf, "abcdefghiuaoiegboegboub", 16); // Buffer overflow
}
int main(void)
{
while(1) {
debugPrint("Hello nxdk!\n");
tfunc();
Sleep(2000);
}
return 0;
}
```
> vcruntime: Implement stack smashing detection

- Makefile
This removes the `-Wno-ignored-attributes` parameter from `NXDK_CFLAGS`. It doesn't appear to produce any difference when building nxdk code, not even when also using `-Wall -pedantic`.
> build: Remove -Wno-ignored-attributes clang parameter

- Makefile
- lib/winapi/thread.c
This updates the submodule to include the latest changes to PDCLib, such as using the `IMAGE_TLS_DIRECTORY_32` struct from winapi, the added workaround for LTO symbol issues, the SafeSEH fix for `_tls_array.s`, the renamed entry point and the initialization of the stack protection cookie on startup.
> pdclib: Update submodule to 54341cc

- lib/hal/audio.c
- lib/hal/audio.h
- lib/hal/video.h
- lib/hal/xbox.h
- lib/winapi/processthreadsapi.h
- lib/winapi/windef.h
- lib/winapi/winmm/timeapi.h
- lib/xboxrt/vcruntime/purecall.c
Fixes #468.
Fixes a bunch of C function declarations/definitions that were using the old syntax `()`, but should've used `(void)` instead. The only part of code in the nxdk repo that now triggers a `-Wstrict-prototypes` warning is the (old) USB stack.
Also fixes a call where `XAudioPause` was incorrectly called with a parameter.
> Fix strict prototype warnings

- lib/xboxkrnl/xboxkrnl.h
This fixes some issues in the doxygen comments in `xboxkrnl.h`, like missing parameters names and a missing description.
Fixes #473.
> xboxkrnl: Fix documentation errors

- Makefile
- lib/net/nforceif/include/arch/cc.h
- samples/httpd/main.c
- samples/httpd_bsd/httpserver.c
- samples/httpd_bsd/main.c
Apart from the inconsistencies around the code base this has caught me out a few times.
If a user applications has a header file that shares the same name as the hal libs and is in a directory included by `-I` it will include the nxdk's header instead of the application. This is quite common as the hal libs use really common basic filenames.
i.e, if the user application has:
```
inc/debug.h
inc/input.h
```
instances of `#include <debug.h>` or `#include <input.h>` in the user application will include nxdk's headers instead of the users potentially causing some not immediately obvious errors. Using `"` or `< >` makes no difference in this instance.
This was mentioned here:
https://github.com/XboxDev/nxdk/pull/457#discussion_r615170326
This PR makes it so all nxdk hal includes must have …
> Make hal includes relative to lib/ folder

- Makefile
- lib/xboxrt/c_runtime/_alldiv.s
- lib/xboxrt/c_runtime/_allmul.s
- lib/xboxrt/c_runtime/_allrem.s
- lib/xboxrt/c_runtime/_allshl.s
- lib/xboxrt/c_runtime/_allshr.s
- lib/xboxrt/c_runtime/_aulldiv.s
- lib/xboxrt/c_runtime/_aullrem.s
- lib/xboxrt/c_runtime/_aullshl.s
- lib/xboxrt/c_runtime/_aullshr.s
- lib/xboxrt/c_runtime/chkstk.s
- lib/xboxrt/prelude.s.inc
This modifies the assembly files to include the special symbol and value that marks them as SafeSEH compatible. It also removes the linker parameter that was necessary previously.
This does not implement or enable SafeSEH, it only makes the code compatible.
> xboxrt: Make assembly files SafeSEH-compatible

- lib/xboxkrnl/xboxkrnl.h
Closes #476 
I took some of MSDN as reference, but also https://doxygen.reactos.org/d0/d35/ntoskrnl_2ex_2interlocked_8c_source.html for some guidance.
I didn't check for completeness or correctness - but this is enough to get some code to compile that I had.
Please review before merge + feel free to fixup in my branch (I'm not sure when I'll find time to integrate any review feedback myself).
> xboxkrnl: Add volatile keyword to atomic operation functions

- lib/net/pktdrv/pktdrv.c
Having link speed and EEPROM MAC address debugPrint'ed on startup is not always desirable.
Setting `NXDK_NET_SILENT` to `y` in your Makefile removes this clutter.
> pktdrv: Silence network init

- lib/winapi/Makefile
- lib/winapi/winnt.c
- lib/winapi/winnt.h
Implements `InterlockedExchangePointer`, `InterlockedCompareExchangePointer` (both as xboxkrnl wrappers) and `InterlockedExchange64`, all of which are requirements of #321. Sample code for testing the latter is below.
<details>
<summary>main.c</summary>
```c
int main(void)
{
LONG64 target = 0xDEADBEEFBEEFC0DE;
LONG64 value =  0x0123456789123456;
LONG64 result = InterlockedExchange64(&target, value);
debugPrint("target: 0x%08X%08X\n", ((int)(target >> 32)), ((int)(target & 0xFFFFFFFF)));
debugPrint("result: 0x%08X%08X\n", ((int)(result >> 32)), ((int)(result & 0xFFFFFFFF)));
debugPrint("value: 0x%08X%08X\n", ((int)(value >> 32)), ((int)(value & 0xFFFFFFFF)));
// Expected output: …
```
> winapi: Implement more interlocked functions

- lib/net/Makefile
Hi 🙋‍♀️ 
This PR addresses #454 by adjusting the `nxdk/lib/net/Makefile` to yield a `nxdk/lib/libnxdk_net.lib`.
I'm unsure about my work:
- I could have moved the inclusion of `nxdk/lib/net/Makefile` from `nxdk/Makefile` to `nxdk/lib/Makefile`
- The include `CFLAGS` for net are in the net-Makefile, I could have moved them into `nxdk/Makefile`(following the other libs examples(hal, pdclib, winapi, etc.). But that feels wrong - so I wonder, why are the other libs included there and not in their own Makefile(i.e. like libpng does)?
- Why does the net-Makefile has extra `CXXFLAGS` while other libraries don't? Can't find the reason 🙈😅
- Why can we do `#include <hal/debug.h>` but do `#include "lwip/debug.h"` in the samples? ("" vs <>) I switched it to <> and it still works. Note: I know the …
> net: Use own Makefile, build as library

- samples/gamma-fade/Makefile
- samples/gamma/Makefile
- samples/hello++/Makefile
- samples/hello/Makefile
- samples/httpd/Makefile
- samples/httpd_bsd/Makefile
- samples/led/Makefile
- samples/mesh/Makefile
- samples/sdl/Makefile
- samples/sdl_gamecontroller/Makefile
- samples/sdl_image/Makefile
- samples/sdl_ttf/Makefile
- samples/triangle/Makefile
- samples/winapi_drivelist/Makefile
- samples/winapi_filefind/Makefile
- samples/xaudio/Makefile
This allows overriding the `NXDK_DIR` variable in the samples Makefiles by using the `?=` operator, which only assigns a value if the variable is not defined already. It allows to build the samples with the Docker image and sets a better example.
> samples: Allow overriding NXDK_DIR

- .ci_build_samples.sh
- .github/workflows/build_docker_image.yml
- .github/workflows/build_samples.yml
```
.ci_build_samples.sh:
Use one less cd command.
chmod +x
Upgrade checkout to v2.
Use -e when invoking shell(s).
Run .ci_build_samples.sh directly.
build_samples.yml:
Don't use multi-line syntax for one command.
Windows:
Opt out of PowerShell telemetry.
Use curl instead of Invoke-WebRequest.
macOS:
Move exported variables to env:.
Opt out of brew analytics.
Simplify ci_build_samples commands.
Ubuntu:
Remove unneeded packages.
Remove unneeded PATH addition.
```
> ci: Update existing GitHub workflows

- lib/hal/debug.c
- lib/hal/debug.h
- lib/pbkit/pbkit.c
- lib/xboxrt/c_runtime/check_stack.c
- samples/winapi_drivelist/main.c
- samples/winapi_filefind/main.c
This enables format string checking for `debugPrint()`. This means that errors like this can be caught by the compiler and a warning will be issued:
```
debugPrint("i: %d\n"); // ,i is missing
```
I (and others) have been bitten by this kind of error a few times already while debugging.
Format string warnings caused by the code in the nxdk repo are fixed by the other commits, but there are remaining ones in the submodules.
> Format string checking

- lib/hal/video.c
- lib/nxdk/format.c
As discussed in https://github.com/XboxDev/nxdk/issues/491#issuecomment-856235343 the tool chain currently uses many kernel exports which are unable to be properly optimized by the compiler. We should strive to move away from such exports, example Nt class exports.
Another example although unused in the tool chain itself is `XboxHardwareInfo` which is a struct containing information from known memory locations (but the compiler doesn't know this). We should ideally offer a way for users to get this information without relying on the kernel (or having to know the exact memory location of the values).
> Use less kernel exports where appropriate

- .dockerignore
- .github/workflows/build_docker_image.yml
- .github/workflows/build_samples.yml
- Dockerfile
- Makefile
- samples/usb/Makefile
This includes a few changes to improve our Docker images:
* Update the base from Alpine 3.12 to 3.13
* Use a multi-stage Dockerfile to reduce the size of the final image by not including unnecessary Alpine packages
* Prebuild the libraries and tools in the images
* Don't include the samples in the image
* Provide and test three images: nxdk, which is built with -02, nxdk-debug, which is built with debug info, and nxdk-lto, which is built with -O2 and LTO enabled
* Use a build matrix for the Docker images to keep the total runtime of the Actions low (was about 10m without the matrix)
* Add some metadata, like the build time, licenses, repository URL, git revision etc.
a7eee3906108b543c2378bd6e904c4630470a6d2 is a bit of a band-aid for our build system. I'm not too happy about it, but I …
> Docker improvements

- lib/usb/libusbohci_xbox/xid_driver.c
This is a bug I missed in the initial xid driver.
Upsteam usb host lib manages devices by linked lists, so I did the same, however I missed the case if the device is at the head of the list.
SDL_Gamecontroller API almost makes this a non-issue which is why I missed it, but under some scenarios calling `SDL_XBOX_JoystickGetDevicePlayerIndex` or `SDL_XBOX_JoystickGetCount` may not return the expected values. It becomes a bigger is working with the driver directly.
You can recreate the issue using the SDL Gamecontroler sample:
1. Connect a controller to port 1.
2. Controller a controller to port 2.
3. Disconnect then reconnect port 1.
4. Connect a controller to Port 3. The controller index will be '1', but it should be '2' (0 = First controller)
You can also see this issue more clearly using …
> usb: Fix xid device removal

- lib/winapi/winnt.h
`LibraryFlags` had the wrong size. The erroneous size came from caustik's XBE doc.
I noticed the error while looking at an XBE in Ghidra, and confirmed that `WORD` is indeed correct by comparing with the cxbe code.
> winapi: Fix size of LibraryFlags in XBE_LIBRARY_HEADER

- lib/winapi/fileapi.h
- lib/winapi/filemanip.c
Implements `SetFileTime()` and `GetFileTime()` (I just read up on file attributes again and decided to go for these). Not tested beyond compilation yet.
Fixes #470
> winapi: Implement SetFileTime()/GetFileTime()

- lib/hal/video.c
This reverts #424, but adds code that deletes a persistent framebuffer if one exists, so that #357 stays resolved.
I was looking into why #507 might happen for #509, and found that the issue is most likely caused by a fundamental issue with how we treat the allocated memory. Our code treats the memory like it just contains the plain framebuffer, while the XDK code in the dash expects to find a `D3DSurface` (name derived from Cxbx-Reloaded) struct describing the framebuffer, with the data following after that. Rebooting from our code to the dash would then pass a corrupted struct to the dash, which I assume is the reason for the screen corruption. This would also affect other any other xbe launched from nxdk code, hence the removal.
Allowing proper handling of framebuffer persistence is a …
> Revert #424, free persistent framebuffer

- bin/activate
Was receiving the following error when attempting to build within WSL2 due to the path not being wrapped in quotes. Additional changes are needed to fully support spaces within the `NXDK_PATH` however.
```
mike@MJD0029:~/projects/nxdk/bin$ ./activate
./activate: 11: export: Files/WindowsApps/CanonicalGroupLimited.Ubuntu20.04onWindows_2004.2021.825.0_x64__79rhkp1fndgsc:/mnt/c/Program: bad variable name
```
> build: Fix activate script within WSL environment

- Dockerfile
While going through a GH Actions log, I realized that the Docker container was no longer building the samples, despite the command exiting without an error. Checking the Docker docs, I realized that the two different syntaxes for `ENTRYPOINT` have different behavior, and the one we were using was suppressing cli arguments, so our entrypoint script was getting no command to run, and just happily quit.
Due to this screw-up on my part, all Docker images built since https://github.com/XboxDev/nxdk/pull/518 was merged were broken.
> build: Fix Docker entrypoint not getting cli arguments

- lib/nxdk/automount_d.c
- lib/winapi/fiber.c
This, together with https://github.com/XboxDev/nxdk-pdclib/pull/48, fixes the issue where constructors were run before thread-local storage was available by running them from the main thread instead of the startup thread. However, `fls_init` is a special constructor that needs to run before any thread creation, so this introduces and uses a new mechanism which allows for constructors to run in the startup thread instead by putting function pointers in a custom subsection of `.CRT` (the same thing is done automatically by the compiler for regular constructors).
This code can be used to verify that the change works. Before the changes, this would crash during the construction of the global `std::stringstream s`, but with the changes, it should run correctly.
```c++ …
```
> winapi: Run fls_init in startup thread, before regular constructors

- lib/nxdk/Makefile
- lib/nxdk/xbe.c
- lib/nxdk/xbe.h
- lib/winapi/winnt.h
- lib/xboxkrnl/xboxdef.h
- lib/xboxkrnl/xboxkrnl.h
Title pretty much says it all. Can be tested with something simple like this (output will usually be 11000):
```
PXBE_SECTION_HEADER xh = nxXbeGetSectionByName(".text");
if (xh) {
debugPrint("%lx\n", xh->VirtualAddress);
}
```
Closes #477.
> nxdk: Provide function to find XBE section by name

- lib/winapi/fileapi.h
- lib/winapi/filemanip.c
This changes the parameter type for these two functions from `LPCTSTR`(a const T-string pointer) to `LPCSTR` (a const ASCII-string pointer).
Closes #502
> winapi: Fix MoveFileA/DeleteFileA parameter type

- bin/nxdk-cc
- bin/nxdk-cxx
The current git version of clang, which will become clang 14 once released, defines `__STDC_NO_THREADS__`, because MSVC does not provide C11 threads: https://reviews.llvm.org/D112081
nxdk, however, does, and the define breaks building our C11 threads implementation. This adds a parameter to our compiler wrappers to remove that define again.
Tested with this morning's git version of LLVM (https://github.com/llvm/llvm-project/commit/75db002725156fba9e9c38b7cefe57b7ed713734).
> build: Undefine __STDC_NO_THREADS__ for compatibility with clang 14

- bin/activate
This fixes a small issue I noticed when experimenting with a Debian Docker image.
Running `bin/activate` would fail there, because not going through a normal login process leaves `$SHELL` unset. `bash`, which is used as the default interactive shell in the image, seems to have an integrated fallback for that, which simply inserts a path to `bash` itself whenever `$SHELL` is used but not set, but `dash`, which is used as the standard shell for scripts, does not.
Therefore, this adds a fallback to `sh` if `SHELL` is unset, which makes the script work ootb.
> build: Add fallback for situations where $SHELL is unset

- lib/zlib/Makefile
When building https://github.com/MakeMHz/xbox-hd-plus-app
I got the following
```
#include <zlib.h>
^~~~~~~~
1 error generated.
```
This change in the makefile resolved the problem and I was able to build successfully.
> zlib: Fix build against CXX project

- lib/xboxkrnl/xboxkrnl.h
Fixes part of #537
The type signature of these methods matches Microsoft but has caused confusion and is not entirely aligned with expectations around how IO space is generally referenced. Since we want to keep the type in sync with the [MS docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-read_port_buffer_uchar) and implementation, the decision was made to attempt to resolve this confusion via documentation.
> xboxkrnl: Add documentation for *_PORT_BUFFER_* methods

- lib/hal/debug.c
I got a crash caused by debugPrint which took me a long time to solve.
The cause was me debugging with too much debug info to debug this debug issue.
Currently this just fails silently in a crash from an overflow. This PR makes it use snprint instead.
> debug: Use safer print formatting

- lib/nxdk/format.c
This fixes a warning about implicitly declaring `memset` in `format.h`, apparently I forgot to include the `string.h` header.
> nxdk: Fix implicit declaration warning in format.c

- lib/xboxkrnl/xboxdef.h
- lib/xboxrt/vcruntime/excpt.h
After writing some verbose information when exception is raise. I found out CONTEXT flags and GetExceptionInformation macro are missing.
By having these changes upstream can allow [xbox kernel test suite](https://github.com/Cxbx-Reloaded/xbox_kernel_test_suite) to use them directly for testing purpose.
If there are any further addition needed, feel free to update this pull request.
> Add several missing exception usage

- lib/xboxkrnl/xboxkrnl.h
These two commits are split out from `nvnetdrv`, the new NIC driver Ryzee and I worked on. They are useful for reading EEPROM settings (such as the Ethernet address) and for waking up a thread using an event while also boosting thread priority (used by `nvnetdrv`'s IRQ processing).
I'm submitting these commits separately because they're also used by the network configuration API I'm working on that I plan to submit before `nvnetdrv` to make the transition easier.
> xboxkrnl: Add some necessary constants

- lib/hal/xbox.c
- lib/hal/xbox.h
- lib/xboxkrnl/xboxkrnl.h
* Adds an extended version of `XLaunchXBE` that allows the `LaunchData` member to be set on the persisted launch data struct.
* Adds a helper method to retrieve the launch type and data (with handling of the launch-from-dashboard case).
Basic test at abaire/nxdk_launch_test
Note that there seems to be a bug in the handling of "D:" prefixed paths (see #500).
> Expands XLaunchXBE to allow caller to set LaunchData.

- lib/hal/audio.c
- lib/hal/audio.h
I have managed to find the original authors and got their permission to relicense this under the MIT license (I can share proof of the conversations in a non-public channel on request).
I've combined the license change with adding proper attribution by using SPDX-tags.
> hal: Relicense audio code to MIT

- Dockerfile
- lib/pbkit/pbkit.c
- lib/pbkit/pbkit.h
I have managed to find the original author and got his permission to relicense this under the MIT license (I can share proof of the conversation in a non-public channel on request).
I've combined the license change with adding proper attribution by using SPDX-tags.
Fixes #448
> pbkit: Relicense under MIT

- lib/Makefile
- lib/pbkit/Makefile
Builds pbkit to `libnxdk_pbkit.lib`, similar to the other libraries
> pbkit: Build as library

- lib/winapi/fiber.c
This fixes a crash that happens when building `winapi` with LTO. LLVM detects there are no references to `__fls_init_p` (it is never called directly, only via iterating over the `.CRT$XXT` subsection which contains these special constructors)  and removes it, but this function pointer is necessary to initialize the variables used by `fls_register_thread`, which is run whenever a new thread is created. The uninitialized variables cause the latter function to cause a crash in kernel code.
The fix is to force the linker to include the symbol whenever the object file containing `fls_register_thread` is being included.
Fixes #552.
My initial checks with LLVM 13.0.1 suggested that this is only an issue with specific versions of LLVM, however, I've been able to reproduce it with this version now …
> winapi: Fix LTO optimizing away the fls_init constructor

- lib/pbkit/Makefile
Renaming the pbkit lib output to libpbkit. Since it isn't part of nxdk itself, it should be distinct.
> pbkit: Rename lib to libpbkit

- LICENSES/Apache-2.0.txt
- LICENSES/CC0-1.0.txt
- LICENSES/MIT.txt
- LICENSES/NCSA.txt
This adds the license files that are relevant to nxdk itself, located in a `LICENSE` folder as demanded by the REUSE specification. Licenses were downloaded with `reuse download <licensename>`.
> license: Add missing license files

- tools/cxbe/Common.cpp
- tools/cxbe/Common.h
- tools/cxbe/Cxbx.h
- tools/cxbe/Error.cpp
- tools/cxbe/Error.h
- tools/cxbe/Exe.cpp
- tools/cxbe/Exe.h
- tools/cxbe/Logo.cpp
- tools/cxbe/Main.cpp
- tools/cxbe/Xbe.cpp
- tools/cxbe/Xbe.h
This changes cxbe's license and copyright statements to use SPDX like we do for other code already, which reduces verbosity and is machine readable (there are tools to check license conformity etc.).
> cxbe: Simplify license statements and attribution with SPDX

- lib/nxdk/automount_d.c
- lib/nxdk/fatx.h
- lib/nxdk/format.c
- lib/nxdk/format.h
- lib/nxdk/mount.c
- lib/nxdk/mount.h
- lib/nxdk/path.c
- lib/nxdk/path.h
- lib/nxdk/xbe.c
- lib/nxdk/xbe.h
This adds SPDX-style license and copyright statements to the nxdk library code.
> nxdk: Add SPDX license and copyright info

- LICENSES/LicenseRef-NVIDIA-CG.txt
- tools/cg/linux/cgc.i386.license
- tools/cg/linux/cgc.license
- tools/cg/mac/cgc.license
- tools/cg/win/cgc.exe.license
This adds the copyright and license info for the Cg binaries we distribute.
> cg: Add NVIDIA license info

- .ci_build_samples.sh
- .editorconfig
- .gitignore
- .gitmodules
- Dockerfile
- bin/activate
- bin/nxdk-as
- bin/nxdk-cc
- bin/nxdk-cmake
- bin/nxdk-cxx
- bin/nxdk-lib
- bin/nxdk-link
- bin/nxdk-pkg-config
- samples/xaudio/nxdk.wav.license
This adds SPDX-style licensing info to some of our smaller files that don't warrant a separate PR, such as the build scripts.
> Add license info to smaller files

- lib/xboxkrnl/ntstatus.h
- lib/xboxkrnl/xboxdef.h
- lib/xboxkrnl/xboxkrnl.exe.def
- lib/xboxkrnl/xboxkrnl.h
This replaces the non-standard and missing license and copyright statements in `xboxkrnl` files with SPDX.
> xboxkrnl: Improve licensing info

- Makefile
- lib/net/nforceif/include/lwipopts.h
- lib/nxdk/Makefile
- lib/nxdk/configsector.c
- lib/nxdk/configsector.h
- lib/nxdk/net.c
- lib/nxdk/net.h
- samples/httpd/main.c
- samples/httpd_bsd/main.c
This adds a new network initialization API, with the ability to read and use the settings from the HDD. This is a breaking change, and the samples have been adapted accordingly. When using this API, there shouldn't be another breaking change when our new NIC driver lands.
The three supported ways to initialize are `AUTO`, which will try to use the config sector (this is the same as passing `NULL` to `nxNetInit`), `DHCP`, and`STATIC`. All three modes allow overriding the DNS settings by setting the DNS fields to a non-null value.
The static IP fields are simple `uint32_t` to not introduce a dependency on headers from other libraries, especially since I plan to add a wrapper to provide the winsock API in the future.
A shutdown function is not provided because lwIP doesn't provide a way for …
> network init API

- lib/nxdk/net.h
Fixes building C++ applications with networking support.
> nxdk: Add C++ guard to net.h

- lib/winapi/sync.c
- lib/winapi/synchapi.h
Add CreateMutex and ReleaseMutex synchapi.h functions
I did a basic test with this code:
```
#include <assert.h>
static HANDLE mutex;
static HANDLE thread;
static int mutex_variable;
DWORD WINAPI increment_variable(LPVOID arg)
{
while (1)
{
WaitForSingleObject(mutex, INFINITE);
//We have a lock on mutex_variable. Do a couple independent non atomic operations
//with a big delay between them to test the mutex lock.
mutex_variable++;
//Put thread to sleep for a while. If we access mutex_variable from another thread during this sleep,
//it will be an odd number! Shouldnt happen if mutex is working!
Sleep(1000);
mutex_variable++;
ReleaseMutex(mutex);
}
return TRUE;
}
int main(void)
{
XVideoSetMode(640, 480, 32, …
```
> winapi: Add Mutex functions

- lib/hal/video.c
- lib/hal/video.h
I had a need to read the widescreen video flag set by MSDash and realised we did not have this defined.
I took the liberty of adding some others and removed some of the magic numbers in video.c
> video: Add additional video defines

- bin/nxdk-pkg-config
It runs as `sh` and so should be POSIX shell compatible.
> bin/nxdk-pkg-config: Fix bashism

- lib/winapi/fileapi.h
- lib/winapi/fileio.c
In agreement with @kosmas12 this supersedes #556. The code itself is rather old (May 2021, for some reason I didn't upstream it and forgot about it), I just rebased and tested it today.
Closes #471 
Simple test code (this will truncate the file `test.bin` in the same directory as the XBE, I tested with a 1MiB file full of zeroes):
```C
int main(void)
{
HANDLE h = CreateFile("D:\\test.bin", GENERIC_ALL, FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
if (h == INVALID_HANDLE_VALUE) {
debugPrint("Error: %x\n", GetLastError());
Sleep(10000);
return 0;
}
SetFilePointer(h, 512*1024, NULL, FILE_BEGIN);
SetEndOfFile(h);
CloseHandle(h);
debugPrint("Done!\n"); …
```
> winapi: Implement SetEndOfFile()

- lib/xboxrt/libc_extensions/stdlib_ext_.h
This should provide the necessary functionality to get libc++'s aligned `new` working. Depends on https://github.com/XboxDev/nxdk-pdclib/pull/52
> libc: Provide MS's _aligned_malloc() / _aligned_free()

- lib/xboxrt/vcruntime/purecall.c
`purecall.c` was including the extension header `stdlib_ext_.h` instead of the proper `stdlib.h`, causing a warning due to the former's use of `aligned_alloc`, which is declared in the latter.
Fixes https://github.com/XboxDev/nxdk/issues/612
> vcruntime: Fix warning caused by including stdlib_ext_.h

- lib/nxdk/net.c
This fixes the DNS overriding behavior in the nxdk network initialization API. Despite being called `numdns`, `dns_setserver`'s first parameter is *not* a count, it's an index. This resulted in DNS overriding having no actual effect.
This change fixes that, and also only overrides the setting when the specified IP is valid.
> nxdk: Fix DNS server overriding

- lib/nxdk/configsector.c
- lib/nxdk/configsector.h
This implements saving the network config sector. I tested it with the following code, and the resulting config sector was accepted and correctly decoded by the 5960 dash:
```c
nxdk_network_config_sector_t config;
nxLoadNetworkConfig(&config);
config.manual.secondaryDns = 0xF0F0F0F0;
nxSaveNetworkConfig(&config);
```
> nxdk: Implement support for saving the network config sector

- lib/hal/fileio.c
- lib/hal/fileio.h
I got the original authors' permission to relicense this code under the MIT license. I can share proof of this on Discord on request, and have already shown it to @Ryzee119.
There was a commit by Carcharius, who I haven't been able to contact yet, but it only touched code that we already removed.
> hal: Relicense fileio code to MIT

- README.md
- lib/hal/video.c
- lib/hal/video.h
- lib/hal/xbox.c
- lib/hal/xbox.h
This relicenses the remaining OpenXDK code.
This change was delayed because I haven't been able to contact one the contributors, Carcharius. After multiple unsuccessful attempts I looked closely at the code he contributed, and most of the changes are no longer part of the code as it is used in nxdk. The only remaining work contributed by him are some constants in the video mode table, which can be considered facts, and those are not copyrightable.
> Relicense remaining OpenXDK code

- lib/net/Makefile
- lib/net/nforceif/include/lwipopts.h
- lib/net/nvnetdrv/nvnetdrv.c
- lib/net/nvnetdrv/nvnetdrv.h
- lib/net/nvnetdrv/nvnetdrv_lwip.c
- lib/net/nvnetdrv/nvnetdrv_regs.h
- lib/nxdk/net.c
- lib/xboxkrnl/xboxkrnl.h
This is a replacement network driver that intends to improve network performance of nxdk and replace pktdrv. Will close https://github.com/XboxDev/nxdk/issues/460 and https://github.com/XboxDev/nxdk/issues/129.
This work was started by @thrimbor and I kind of took it over.
~Relies on https://github.com/XboxDev/nxdk/pull/610.~
It has a few key improvements over pktdrv:
* Zero-copy TX and RX transmission
* Automatic scatter gather of TX packets that cross page boundaries so the user doesnt need to worry about it (Up to one page crossing, which should cover all ethernet frame lengths required for 100Mbit)
* Multithreaded buffer manager
* Supports different ring sizes for TX and RX so you can optimise your application for specifc directions to reduce RAM usage. Defaults to 64/64 which seems …
> Replace pkdrv with nvnetdrv

- .github/workflows/build_docker_image.yml
- .github/workflows/build_samples.yml
- Dockerfile
Our previous base image (Alpine 3.13, LLVM 10) seemed to cause broken builds in some cases (`xblunblock` is impacted by this). The newer image is based on Alpine 3.17 with LLVM 15, which worked better in my testing.
I took the chance to also update the Actions we're using (and slightly modify the token usage), since the old versions cause warnings now due to being based on node.js 12.
/edit: This is necessary to fix `xblunblock`'s CI, so I might self-merge in a few days.
> Docker & Actions updates

- lib/xboxkrnl/xboxkrnl.h
- lib/xboxrt/vcruntime/excpt.cpp
This is the problem that has been causing issues for https://github.com/insignia-live/xblunblock
It was caused by `RtlUnwind` not following the stdcall calling convention and overwriting values in registers that are supposed to be callee-saved. This didn't cause any problems when building without optimizations, but adding `-O2` and trying to catch exceptions made this problem appear due to the compiler inlining `_global_unwind2`, resulting in a jump to a null pointer.
The solution here is to add all registers (except `eax`, which is used for pushing the parameter) to the clobber list, making the compiler save the registers that are still needed.
Some other minor changes are also included, like making sure the compiler doesn't reorder memory accesses across `cld` and marking the exception …
> vcruntime: Fix crashes in SEH handling when enabling optimizations

- lib/xboxkrnl/xboxkrnl.h
Nothing much to say. Just a simple typo fix.
Fixed typo in RemoveHeadList macro variable name.
> Fix typo in RemoveHeadList macro

- lib/net/nforceif/include/arch/cc.h
This removes a few bits of unnecessary preprocessor stuff and whitespaces, and removes the redefinition of `fflush` and `printf` that could cause some issues with header include order.
> net: Whitespace and macro cleanup in cc.h

- lib/xboxkrnl/xboxkrnl.h
When I was troubleshooting an issue with Area 51 title in Cxbx-Reloaded for a false positive successful by handle given with -1 from ObReferenceObjectByHandle function. I decided to verify the test on hardware if there is such special case for -1 from embedded kernel. After test was made and receive result, I only got `0x8` and `0x24` instead of `0xc0000008` and `0xc0000024` status.
After a fix with return type from BOOL to NTSTATUS, it now receive `0xc0000008` and `0xc0000024` status properly. I also discover this issue could affect `/lib/winapi/thread.c` file as well.
> kernel: fix ObReferenceObjectByHandle return type

- lib/net/nvnetdrv/nvnetdrv_lwip.c
This PR modifies the return type of ``low_level_init()`` inside of nvnet to allow it to pass an error back to ``nvnetif_init()`` on failure to initialize. 
With a retail kernel, calls to ``ExQueryNonVolatileSetting`` can fail if the EEPROM is corrupt. In its current state, nxdk, will bail via ``abort()`` after the call [here](https://github.com/XboxDev/nxdk/blob/4070510f2916745e1794050a101b9e7b4acf465a/lib/net/nvnetdrv/nvnetdrv.c#L406) to ``ExQueryNonVolatileSetting``.
This PR addresses the above-mentioned issue and allows for the application to handle if nvnet was successful, or not, in initialization.
> net: Allow for initialization to gracefully fail

- lib/xboxkrnl/xboxdef.h
- lib/xboxkrnl/xboxkrnl.h
Missing addition of OBJECT_HEADER in nxdk repo will allow me to prepare upload xbox_object_directory_list project on GitHub. Having access to OBJECT_HEADER allow me access to pointer of Type member variable to determine which type of object it is.
> xboxkrnl: add OBJECT_HEADER structure

- share/toolchain-nxdk.cmake
Sets CMAKE_<LANG>_STANDARD_INCLUDE_DIRECTORIES for cc and cxx compilers. This allows tools like CLion to properly index the cross-compiler headers.
> cmake: Set STANDARD_INCLUDE_DIRECTORIES

- tools/cxbe/Exe.cpp
- tools/cxbe/Exe.h
- tools/cxbe/Xbe.cpp
- tools/cxbe/Xbe.h
This implements handling for `dwNonKernelImportDirAddr` in DEBUG mode, allowing nxdk-based XBEs to make use of `xbdm.dll` and other non-kernel imports.
> cxbe: Support non-kernel imports

- tools/cxbe/Exe.cpp
- tools/cxbe/Xbe.cpp
Switches use of sprintf to snprintf to prevent a bunch of clang deprecation warnings.
> cxbe: Fix sprintf compiler warnings

- lib/winapi/sync.c
- lib/winapi/synchapi.h
I need asynchronous File IO using overlapped functions which is [not currently supported](https://github.com/XboxDev/nxdk/blob/9daebb58281125c6e0b7be8ebd36e93be06db63f/lib/winapi/fileio.c#L107). Win32 uses  [Event Objects](https://learn.microsoft.com/en-us/windows/win32/sync/event-objects) to achieve this.
This is the first step to support overlapped IO.
Usage example below that simply has a sleeping thread wait for an event. Also tests some error scenarios.
```c
#include <stdio.h>
#include <assert.h>
static DWORD WINAPI EventThread(LPVOID lpParam)
{
HANDLE hEvent = (HANDLE)lpParam;
while (1) {
if (WaitForSingleObject(hEvent, INFINITE) == WAIT_OBJECT_0) {
debugPrint("Thread received the event!\n");
}
}
return 0;
}
int …
```
> winapi: Add Event functions

- lib/winapi/Makefile
- lib/winapi/sysinfo.c
- lib/winapi/sysinfoapi.h
- lib/winapi/timezoneapi.c
- lib/winapi/timezoneapi.h
- lib/winapi/windows.h
- lib/xboxkrnl/xboxkrnl.h
This PR adds [GetLocalTime](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getlocaltime). This requires [GetTimeZoneInformation](https://learn.microsoft.com/en-us/windows/win32/api/timezoneapi/nf-timezoneapi-gettimezoneinformation) so is also added in this PR.
`GetTimeZoneInformation` reads the timezone biases, and daylight savings start/end times from the Xbox EEPROM and calculates whether the user is in DST or not and returns a TIME_ZONE_INFORMATION struct with all the timezone information. These EEPROM values are written by MSDash when you set your timezone.
This is used by `GetLocalTime` to determine the users current time based on the SystemTime.
DST is automatically adjusted for when the corresponding setting in MSDash is enabled (and your timezone …
> Add GetLocalTime function

- .github/workflows/build_samples.yml
- tools/cxbe/Exe.cpp
The wonderful Homebrew package manager exits with an error code after refusing to remove symlinks from older versions of packages when updating packages during an install of a new package. Just remove the brew update to avoid the issue. We don't need bleeding edge llvm and will get updates periodically with runner updates anyway.
Replaces newly added `nullptr` usage with `NULL` for older C++ compiler standard compat.
> Fix macOS build

- tools/cxbe/Exe.cpp
- tools/cxbe/Xbe.cpp
Fixes regression introduced by https://github.com/XboxDev/nxdk/commit/d6f0f3a24b35f086889c8d8c2c591656e759fdbb.
The underlying issue is that trailing null bytes are not stored in the exe and thus are not part of `dwSizeofRaw`, causing the null terminator of the `xboxkrnl.exe`-string to get cut off resulting in an oob-read and invalid string comparison, which ultimately produces an xbe with an incorrect import directory (the `hello` sample can be used to test this).
I've changed the exe loader and xbe constructor to instead keep the full section in memory so that valid reads from sections can no longer be out of bounds. This slightly increases memory consumption during the conversion, but that shouldn't be an issue.
> cxbe: Fix oob section reads

- .github/workflows/build_docker_image.yml
I got the feedback that it would be preferred to not push the debug and lto tags to the nxdk repo. This changes that. It also makes sure the push is only done for the master branch. Sorry about that one.
> docker: Only build once and push to repo registry

- .github/workflows/build_docker_image.yml
I accidentally put them to wrong way around. This fixes that.
> docker: Set lto and debug tags for correct containers

- .github/workflows/build_docker_image.yml
Current nxdk master fails because the login action isn't always executed.
> docker: Fix missing authorization when pushing image

- tools/cxbe/Xbe.cpp
A simple test with the hello world example is enough to generate an XBE with an invalid header.
```c
__attribute__((section("TEST")))
void test() {
Sleep(1000);
}
int main(void) {
while(1) {
debugPrint("Hello nxdk!\n");
Sleep(2000);
}
return 0;
}
```
This results in the final section, ``TEST``, being generated with a physical section size greater than the virtual size.
The physical size is calculated [here](https://github.com/XboxDev/nxdk/blob/ed21e83da43b8b8da14a9a78cf2528d9b5df86a7/tools/cxbe/Xbe.cpp#L397). The calculated physical size is 512 bytes in this case since the code section is filled with 0xCC. 
Since this is the last section in the PE, the virtual size is pulled …
> cxbe: Fix broken XBE sections sizes

- lib/winapi/Makefile
- lib/winapi/fileio.c
- lib/winapi/ioapi.c
- lib/winapi/winbase.h
Asynchronous fileio has some limitations ref
https://learn.microsoft.com/en-US/previous-versions/troubleshoot/windows/win32/asynchronous-disk-io-synchronous and 
https://github.com/JayFoxRox/nxdk/pull/45
Asynchronous file read/writes have these requirements generally:
* They must use FILE_FLAG_NO_BUFFERING which has size and alignemnt requirements of the buffer (DWORD alignment and multiple of sector size)
* Writes that increase the file size must preallocate the space.
If these are not met the request will either fail or complete synchronously
Overlapped structure members seemed a bit odd to me when I initially looked at this but this was my reference
https://learn.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-overlapped
Some test code below which demonstrates async read …
> Add overlapped (asynchronous file read/writes) to WinAPI

- bin/activate
This fixes the macOS CI failure on the newer ARM64 runners, caused by homebrew using a different installation path there.
> build: Fix finding LLVM on macOS on ARM64

- bin/nxdk-cc
- bin/nxdk-cxx
- lib/winapi/winnt.h
Fixes https://github.com/XboxDev/nxdk/issues/547
Also fixes the `undefining builtin macro` warnings caused by us undefining `__STDC_NO_THREADS__`.
> Some warning fixes

- lib/winapi/.clang-format
Add a clang-format file specifcally to the winapi folder. The formatting across the `lib/` varies alot with formatting so this atleast targets this one folder that has bitten me a few times with formatting issues., although this also works pretty well for the `nxdk/` folder
This was based on the bare minimum custom options I could find whilst matching the existing format as best as I could.
This results in the following diff when ran against the winapi folder
~~https://github.com/XboxDev/nxdk/commit/2a2392ae51832295061856f5bf2e0779c88520b3~~ comments1
~~https://github.com/XboxDev/nxdk/commit/f22f6eef47f110caf1a733c1e338539b62f04381~~ comments2
~~https://github.com/XboxDev/nxdk/commit/1a2ab65e225508e3c97b6e9868ed7d974b7999fe~~ comments3 …
> winapi: Add clang-format file

- lib/winapi/timezoneapi.c
As mentioned in https://github.com/XboxDev/nxdk/pull/670, GetDayOfWeek() function had an unusual code style and did not behave well with clang-format.
The notation for this function was originally a copy paste of the "Keith" method from https://en.wikipedia.org/wiki/Determination_of_the_day_of_the_week.
This PR refactors the function to a more standard format. The functionality has been verified against the original wiki implementation with the below code .
I changed the function inputs to INTs are that is what the alogirthm calls for. This was technically a bug.
```
#include <assert.h>
static int keith (int y, int m, int d)
{
return (d+=m<3 ? y-- : y-2,23*m/9+d+4+y/4-y/100+y/400) % 7;
}
static UCHAR GetDayOfWeek (INT year, INT month, INT day) {
if (month < 3) {
day …
```
> winapi: Refactor GetDayOfWeek function

- lib/usb/libusbohci_xbox/usbh_config_xbox.h
The USB spec specifies a maximum of 15 endpoints per interface (excluding the control endpoint), this change makes us support that.
Fixes https://github.com/XboxDev/nxdk/issues/675
libusbohci preallocates a lot of stuff, so this increases memory usage per device by about 1KiB.
> usb: Support maximum endpoints per interface specified by USB spec

- .github/workflows/build_samples.yml
The build for macOS is currently failing due to missing `lld` dependency.
Note: If it's preferable I can combine my PRs into one, although it's probably easier to review them separately. Just let me know whatever you prefer.
> ci: Install lld explicitly on macOS

- .ci_build_samples.sh
This PR adds expandable divisions for each section when building samples in CI.
> ci: Add log separators for each sample

- lib/net/nforceif/src/sys_arch.c
Was getting some corruption in the lwip mboxes. This is a bug and the code should be the modulo operator not bitwise AND.
The below code demonstrates the issue
```
static void my_tcpip_callback1(void *param){
DbgPrint("I work\n"):
} 
static void my_tcpip_callback2(void *param){
DbgPrint("I don't work\n"):
}
nxNetInit(NULL);
tcpip_callback(my_tcpip_callback1, NULL); // This works by chance as mbox position is zero.
tcpip_callback(my_tcpip_callback2, NULL); // This doesnt work
```
> lwip: Use modulo operator for mbox

- lib/hal/debug.c
Prevents CR characters being printed like below and is just generally useful to handle CR correctly.
> debug: Handle carriage return

- lib/winapi/processthreadsapi.h
- lib/winapi/thread.c
Needed these, realised we had no winapi wrapper. Tested on xemu and hw with the below code:
```
#include <assert.h>
DWORD WINAPI ThreadProc(LPVOID lpParameter)
{
while (1)
{
debugPrint("Worker thread is running...\n");
Sleep(250);
}
return 0;
}
int main(void)
{
HANDLE hThread = CreateThread(NULL, 0, ThreadProc, NULL, 0, NULL);
// Let thread work for a while
Sleep(1000);
// Suspend the thread 3 times to test count
SuspendThread(hThread);
SuspendThread(hThread);
DWORD dwPreviousCount = SuspendThread(hThread);
// If the function succeeds, the return value is the thread's previous suspend count
assert(dwPreviousCount == 2);
// Ensure thread is suspended
debugPrint("Thread is …
```
> winapi: Implement Suspend/Resume Thread

- lib/net/nvnetdrv/nvnetdrv.c
- lib/net/nvnetdrv/nvnetdrv.h
- lib/net/nvnetdrv/nvnetdrv_lwip.c
- lib/net/nvnetdrv/nvnetdrv_regs.h
This is a culmination of work over ~12 months or so.
With nvnetdrv being used in StellarOS, it has seen many hundreds/thousands of people using it through the online updater and FTP server and a few edges cases started arising.
As part of the debugging effort in collaboration with LoveMhz/StellarOS developers, a significant amount of refactoring and optimizations were done.
This has turned into a reasonably big PR (sorry!) so I'm calling it version 2, however the primary changes are
1. Refactoring of variable names
2. Reduced memory footprint significantly
3. Less threads/context switching
4. Fixes some bugs.
Hopefully I have broken up the commits into logical units.
My stress test involved 8 x parallel iperf connections, 10 parallel FTP connections (with hash check of files after), web …
> nvnetdrv v2 part 1

- lib/winapi/winbase.h
The latest mbedtls release depends on this, and it was easy to implement.
It's basically just like a memset with zeroes or a call to ZeroMemory, but with volatile pointers to keep the compiler from optimizing it out, so it can be used for clearing memory that contained sensitive data.
On Windows this is implement in a header so the compiler can inline it, I did that as well.
> winapi: Implement SecureZeroMemory()

- lib/winapi/sysinfo.c
- lib/winapi/sysinfoapi.h
The latest mbedtls release depends on this, and it was easy to implement, just forwards to `GetSystemTimePreciseAsFileTime` for now.
> winapi: Implement GetSystemTimeAsFileTime()

- share/toolchain-nxdk.cmake
It's a rather trivial change, but the latest mbedtls release needs these two set to build.
> cmake: Set CMAKE_C_COMPILER_AR and CMAKE_C_COMPILER_RANLIB

- .github/workflows/build_samples.yml
- bin/activate
- bin/nxdk-pkg-config
- lib/pkgconfig/SDL2_image.pc
- lib/pkgconfig/SDL2_ttf.pc
- lib/pkgconfig/libjpeg.pc
- lib/pkgconfig/libpng.pc
- lib/pkgconfig/sdl2.pc
- lib/pkgconfig/zlib.pc
The last two commits are from https://github.com/XboxDev/nxdk/pull/631, with only the commit title updated. They make it possible for CMake to find the libraries to link against via pkg-config.
These two commits had the problem that they fix CMake, but by doing so are breaking direct usage of `nxdk-pkg-config` (and probably meson) because the emitted linker arguments are in `ld` syntax, while we rely on the syntax of `link.exe`.
This PR circumvents this issue by switching from whatever pkg-config the host OS provides to explicitly requiring `pkgconf` (which is the default `pkg-config` implementation on Arch, Alpine and probably others anyway).
`pkgconf` provides a `--msvc-syntax` parameter that can be used to get the required `link.exe`-style linker parameters. This would add an …
> Pkgconfig CMake compatibility & switch to pkgconf

- lib/pbkit/pbkit.c
This allows XBDM to stay responsive after an exception.
> pbkit: Sleep in exception handler to prevent debug thread starvation

- Dockerfile
Just an update to a more recent version of Alpine Linux, with LLVM 19
> Update docker base image to git-ee8f698d (based on Alpine 3.21)

- lib/winapi/profiling.c
The first of these two commits changes our implementation of `QueryPerformanceCounter` and `QueryPerformanceFrequency` to use the TSC (like later XDKs did) instead of the kernel's less accurate internal counter.
The second commit improves compatibility with non-stock Xbox systems by using a constructor to compute the TSC frequency on startup instead of using a hard-coded value.
It uses a lookup-table of known CPU clock multipliers and FSB divider and multiplier values from the northbridge to derive this frequency from the crystal frequency. This is done with 64 bit integer math and fractions of a Hz to not introduce any errors during the calculations.
The only way this could be wrong should be using a non-stock crystal frequency.
Using this code in xemu requires …
> Use TSC for QueryPerformance* API

- lib/pbkit/pbkit.c
- lib/pbkit/pbkit.h
This facilitates integration with alternative `printf` implementations that support floats like mpaland/printf.
> pbkit: Expose pb_print_char to allow use of alternative printf

- lib/pbkit/pbkit.c
Fixes #710 
Trivial program used to repro:
```
if ((status = pb_init())) {
debugPrint("pb_init Error %d\n", status);
Sleep(2000);
return 1;
}
pb_show_front_screen();
pb_fill(0, 0, width, height, 0xff202020);
pb_erase_text_screen();
pb_print("Sleeping and rebooting...");
pb_draw_text_screen();
while(pb_busy()) {
/* Wait for completion... */
}
/* Swap buffers (if we can) */
while (pb_finished()) {
/* Not ready to swap yet */
}
Sleep(500);
```
> pbkit: Fix pb_kill softlock in shutdown handler

- lib/net/nvnetdrv/nvnetdrv.c
- lib/net/nvnetdrv/nvnetdrv.h
- lib/net/nvnetdrv/nvnetdrv_lwip.c
Continuation from https://github.com/XboxDev/nxdk/pull/686
Will likely end up in 3 parts.
Primary change here are to pass ring sizes to the init function instead of #defines. Previously we could have different hardware ring size and queue size. Its actually much simpler to just have the hardware ring size exactly the same size as the queue. It also works better with LWIP as we can create pbuf pools to exactly match our requirement.
Most other commits are just some minor bug fixes and house keeping.
This fixes a bug that on soft reset or coming from XDK app where the network would not retrieve an IP address in some cases.
> nvnetdrv v2 part 2

- share/toolchain-nxdk.cmake
The cmake (3.30, at least) ninja buildsystem generation fails to create .d files when using the NXDK toolchain, leading to a lack of any dependencies on header files. This explicitly adds Clang generation commands.
Verified by building with `-d keepdepfile` and running `ninja -t deps` in the generated build dir.
> cmake: Fix ninja depfile generation

- lib/net/nforceif/include/lwipopts.h
- lib/net/nvnetdrv/nvnetdrv.c
- lib/net/nvnetdrv/nvnetdrv_lwip.c
I think this will be my last major PR for this at this moment.
Primary change is significant optimizations to the RX ring. This drops the entire RX ring threading which in hindsight I'm not sure why I made it so complicated. This will reduce memory usage (atleast 2 or 3 pages) and improve performance.
Fixes a race during init because we setup hardware before lwip and if a packet arrived (via irq) before lwip was setup, it would try push it into the uninitialized network stack and could do strange things.
Updates to latest upstream LWIP. This fixes an actual issue we encountered with http downloads and timeouts not clearing correctly.
> nvnetdrv v2 part 3

- lib/pbkit/nv_regs.h
Bit 20 in NV097_SET_CONTROL0 enables perspective corrected texture mapping (and perspective corrected color interpolation D0, D1, B0 and B1). It is always enabled by DirectX.
Left image bit 20 unset, right image bit 20 set:
Quad using two triangles:
Just quad:
(Images from Xbox HW and https://github.com/coldhex/nxdk_pgraph_tests/commit/aa83445899633cf2c2609850cd90f87d2422b8ba)
> pbkit: Add perspective-correct texture mapping bit to control0

- lib/xboxkrnl/xboxkrnl.h
Noticed when reviewing https://github.com/XboxDev/nxdk/pull/725
`PVOID *` would ofcourse be `void **` which isn't correct.
> xboxkrnl: Fix RtlMoveMemory prototype

- lib/xboxkrnl/xboxkrnl.h
As discussed with @MasonT8198 in Discord DMs, this implements my proposal from this comment: https://github.com/XboxDev/nxdk/pull/723#issuecomment-2725864288
`RtlFillMemory`, `RtlMoveMemory` and `RtlZeroMemory` are now implemented as macro wrappers around their libc equivalent by default (which is how it is on modern Windows/MSVC), but the kernel exports can still be used instead by defining `XBOXKRNL_PREFER_KERNEL_EXPORT`.
Solves the same underlying issue as https://github.com/XboxDev/nxdk/pull/723
> xboxkrnl: Default to macro wrapper for Rtl*Memory functions

- bin/activate
There is a bug in these LLVM versions that can cause SSE2 instructions get emitted when optimizations are turned on despite the target not supporting SSE2.
Originally found by @LoveMHz, tracked in https://github.com/llvm/llvm-project/issues/134607 and fixed in https://github.com/llvm/llvm-project/pull/134547
Version 20.1.3 has the fix.
> build: Warn if clang version is in the 19.x.x-20.1.2 range

- Dockerfile
This reverts the docker image back to the Alpine 3.18-based base-image to avoid the compiler bug https://github.com/XboxDev/nxdk/pull/729 warns about.
> Revert "docker: Update to buildbase:git-ee8f698d (based on Alpine 3.21)"

- lib/net/nvnetdrv/nvnetdrv.c
```
/home/sl/Projects/LithiumX/src/libs/nxdk/lib/net/nvnetdrv/nvnetdrv.c:381:36: warning: 'RtlZeroMemory' call operates on objects of type 'struct tx_misc_t' while the size is based on a different type 'struct tx_misc_t *' [-Wsizeof-pointer-memaccess]
381 |     RtlZeroMemory(g_txData, sizeof(g_txData));
|                   ~~~~~~~~         ^~~~~~~~
/home/sl/Projects/LithiumX/src/libs/nxdk/lib/net/nvnetdrv/nvnetdrv.c:381:36: note: did you mean to dereference the argument to 'sizeof' (and multiply it by the number of elements)?
381 |     RtlZeroMemory(g_txData, sizeof(g_txData));
|                                    ^~~~~~~~
1 warning generated.
```
> net: Properly clear memory space for g_txData

- tools/vp20compiler/main.c
Can now use address relative indexing with passed in data. Useful for gpu vertex skinning
> ADD: ARL support to vp20compiler

- Dockerfile
Updates the image to the latest Alpine release after we had to downgrade due to an LLVM bug https://github.com/XboxDev/nxdk/pull/730
Alpine 3.22 released with LLVM 20.1.6 which is outside the affected range (19.x.x-20.1.2).
Also drops glibc from the image as we don't need it for cgc anymore since https://github.com/XboxDev/nxdk/pull/737
> docker: Update to buildbase:git-3a71ed5f (based on Alpine 3.22)

- lib/net/nvnetdrv/nvnetdrv.c
- lib/net/nvnetdrv/nvnetdrv.h
- lib/net/nvnetdrv/nvnetdrv_lwip.c
Previously it was assumed the link state was up at all times.
This implements link state handling. You can now connect the ethernet cable anytime (or unplug) and lwip should handle things better.
> nvnetdrv: Implement link state change handling

- lib/hal/video.c
D3D init:
```
D3DDevice_SetFlickerFilter(5);
D3DDevice_SetSoftDisplayFilter(0);
```
FilterFilter:
```
LAB_8002fda6:
_smbus_write(RegisterBase,bVar5,bVar4);
return;
}
if (DAT_8003b3e4 != 0xe0) {
if (Param == 0) {
bVar5 = 200;
HalReadSMBusValue(DAT_8003b3e4,200,'\0',&Param);
bVar4 = (byte)Param | 0x40;
}
else {
if (Param == 1) {
bVar5 = 1;
}
else if (Param == 2) {
bVar5 = 2;
}
else if (Param == 3) {
bVar5 = 3;
}
else {
bVar5 = 0;
}
HalReadSMBusValue(DAT_8003b3e4,200,'\0',(ULONG *)&Result);
_smbus_write(RegisterBase,200,(byte)Result & 0x80 | bVar5 << 3 | bVar5);
if (Param == 5) {
bVar4 = 0x80;
}
else {
bVar4 = 0;
}
bVar5 = 0x34;
}
goto LAB_8002fda6;
}
```
> video: Disable soften filter on start-up & fix limits for flicker filter

- lib/winapi/fileapi.h
- lib/winapi/filemanip.c
- lib/winapi/sysinfo.c
- lib/winapi/timezoneapi.c
- lib/winapi/timezoneapi.h
- lib/xboxkrnl/xboxkrnl.h
This implements `CompareFileTime`, `FileTimeToSystemTime`, and `SystemTimeToFileTime`. `CompareFileTime` only has an assert to check for null pointer parameters because it has no way to signal an error to the caller.
Also fixes a typo in the `TIME_FIELDS` struct definition.
> Implement `CompareFileTime`, `FileTimeToSystemTime`, and `SystemTimeToFileTime`

- lib/pbkit/pbkit.c
- samples/mesh/main.c
- samples/triangle/main.c
pbkit and the pbkit samples used magic numbers for the `Protect` parameter of  `MmAllocateContiguousMemoryEx`, this changes that to the proper constants.
> pbkit: Use proper PAGE_* protection flags for memory allocations

- lib/winapi/timezoneapi.c
- lib/winapi/timezoneapi.h
I needed this for an application.
I noticed the creation time seemed 1 second or 2 ahead of the current time, however this is present in the system time (before the local time conversion) and from my research appears to be normal.
`FileTimeToLocalFileTime()` does not consider daylight savings changes and just adds on the base timezone bias. msdocs suggest to use `SystemTimeToTzSpecificLocalTime()` if DST correction is also required.
Tested with the following code with the output shown
```
Now (Local): 2025-08-04 16:49:19
Created (Local): 2025-08-04 16:49:20
Created (UTC): 2025-08-04 07:19:20
```
```
#include <nxdk/mount.h>
int main()
{
nxMountDrive('E', "\\Device\\Harddisk0\\Partition1\\");
// Current Local Time
SYSTEMTIME st;
GetLocalTime(&st);
DbgPrint("Now: …
```
> winapi: Implement FileTimeToLocalFileTime()

- lib/xboxrt/Makefile
- lib/xboxrt/libc_extensions/direct.c
- lib/xboxrt/libc_extensions/direct.h
Supersedes https://github.com/XboxDev/nxdk/pull/636
The cwd functions remain stubbed with asserts, however I fixed this comment by JFR https://github.com/XboxDev/nxdk/pull/636#discussion_r1233221554 and return `ENOSYS` for these functions which means "Function not implemented"
Otherwise I just squashed and renamed the commit title, and did some minor formatting cleanup
> libc: Partial implementaion of `direct.h`
